version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: protoc-gen-aip-go
    main: ./cmd/protoc-gen-aip-go
    binary: protoc-gen-aip-go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: protoc-gen-aip-ts
    main: ./cmd/protoc-gen-aip-ts
    binary: protoc-gen-aip-ts
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: protoc-gen-aip-py
    main: ./cmd/protoc-gen-aip-py
    binary: protoc-gen-aip-py
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: firetiger-oss
    name: connect-aip
  draft: false
  prerelease: auto
