// Package connectaip provides the runtime for AIP-shaped REST endpoints
// generated by the protoc-gen-aip-{go,ts,py} plugins.
//
// The runtime forwards HTTP requests received on AIP-style routes (e.g.
// POST /v1/resources, GET /v1/resources/{name}) to the corresponding Connect
// RPC procedure handlers. Server-streaming methods are forwarded to a
// connect-sse Server (see github.com/firetiger-oss/connect-sse).
//
// Most users will not import this package directly; instead, run
// protoc-gen-aip-go on services with google.api.http annotations and call
// the generated NewServiceAIPHandler / NewServiceAIPClient constructors.
// NewServiceAIPClient returns the standard ServiceClient interface emitted
// by protoc-gen-connect-go, so it is a drop-in replacement for
// NewServiceClient — including per-request header propagation via
// connect.Request[T] and connect.Response[T].
package connectaip
