// Code generated by protoc-gen-aip-ts. DO NOT EDIT.

import { create, fromJson, toJson, type DescMessage, type JsonValue, type MessageInitShape, type MessageShape, type Registry } from "@bufbuild/protobuf";
import { type Client, type CallOptions } from "@connectrpc/connect";
import * as pb from "./test_pb";
import { Empty, EmptySchema } from "@bufbuild/protobuf/wkt";

export interface AIPClientOptions {
  headers?: Record<string, string>;
  fetch?: typeof fetch;
  registry: Registry;
}

const codeFromString: Record<string, number> = {
  canceled: 1, unknown: 2, invalid_argument: 3, deadline_exceeded: 4,
  not_found: 5, already_exists: 6, permission_denied: 7, resource_exhausted: 8,
  failed_precondition: 9, aborted: 10, out_of_range: 11, unimplemented: 12,
  internal: 13, unavailable: 14, data_loss: 15, unauthenticated: 16,
};

const httpStatusToCode: Record<number, number> = {
  400: 3, 401: 16, 403: 7, 404: 5, 409: 6, 412: 9, 429: 8, 501: 12, 503: 14, 504: 4,
};

export class AIPError extends Error {
  readonly code: number;
  constructor(code: number, message: string) {
    super(message);
    this.name = "AIPError";
    this.code = code;
  }
}

async function parseErrorResponse(response: Response): Promise<AIPError> {
  const body = await response.text();
  try {
    const json = JSON.parse(body);
    const code = codeFromString[json.code];
    if (code !== undefined) {
      return new AIPError(code, json.message ?? body);
    }
  } catch { /* fall through */ }
  return new AIPError(httpStatusToCode[response.status] ?? 13, body);
}

// biome-ignore lint/suspicious/noExplicitAny: recursive JSON walker
export function sanitizeAny(data: any, registry: Registry): any {
  if (Array.isArray(data)) {
    return data.map((item) => sanitizeAny(item, registry));
  }
  if (data !== null && typeof data === "object") {
    // Only protobuf Any JSON has @type = "type.googleapis.com/..." per
    // proto3 JSON spec. Guards against google.protobuf.Struct values that
    // happen to contain a string @type field (arbitrary JSON-like data).
    const typeUrl = data["@type"];
    if (typeof typeUrl === "string" && typeUrl.startsWith("type.googleapis.com/")) {
      const slash = typeUrl.lastIndexOf("/");
      const typeName = slash >= 0 ? typeUrl.substring(slash + 1) : typeUrl;
      if (!registry.getMessage(typeName)) {
        // biome-ignore lint/suspicious/noConsole: observability for missing schema
        console.warn(
          `[aip] unknown Any type "${typeUrl}" not in registry; collapsed to empty object. Add the schema to anyRegistry to preserve this field.`,
        );
        return {};
      }
    }
    const result: Record<string, unknown> = {};
    for (const key of Object.keys(data)) {
      result[key] = sanitizeAny(data[key], registry);
    }
    return result;
  }
  return data;
}

export function fromJsonAny<T extends DescMessage>(
  schema: T, data: unknown, registry: Registry,
): MessageShape<T> {
  try {
    return fromJson(schema, data as JsonValue, { registry });
  } catch (e) {
    if (e instanceof Error && e.message.includes("not in the type registry")) {
      return fromJson(schema, sanitizeAny(data, registry) as JsonValue, { registry });
    }
    throw e;
  }
}

async function* streamSSE<T>(
  fetchFn: typeof fetch,
  url: string,
  procedure: string,
  message: unknown,
  headers: Record<string, string>,
  signal?: AbortSignal,
  parse: (data: string) => T = (d) => JSON.parse(d),
): AsyncGenerator<T> {
  const response = await fetchFn(url, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json", Accept: "text/event-stream" },
    body: JSON.stringify({ procedure, header: { "Content-Type": ["application/connect+json"] }, message }),
    signal,
  });

  if (!response.ok) {
    throw await parseErrorResponse(response);
  }

  const reader = response.body?.getReader();
  if (!reader) throw new Error("No response body");
  const decoder = new TextDecoder();
  let buffer = "";
  let flags = 0;
  let dataLines: string[] = [];

  let trailerError: AIPError | undefined;
  function processLine(line: string) {
    const trimmed = line.replace(/\r$/, "");
    if (trimmed === "") {
      if (dataLines.length > 0) {
        const data = dataLines.join("\n");
        if ((flags & 2) !== 0) {
          try {
            const trailer = JSON.parse(data);
            if (trailer.error) {
              const code = codeFromString[trailer.error.code] ?? (httpStatusToCode[500] ?? 13);
              trailerError = new AIPError(code, trailer.error.message ?? JSON.stringify(trailer.error));
            }
          } catch { /* malformed trailer, ignore */ }
        } else {
          pending.push(parse(data));
        }
        dataLines = [];
        flags = 0;
      }
      return;
    }
    if (trimmed.startsWith(":flags ")) { flags = parseInt(trimmed.slice(7), 10) || 0; return; }
    if (trimmed.startsWith(":")) return;
    if (trimmed.startsWith("data: ")) dataLines.push(trimmed.slice(6));
    else if (trimmed.startsWith("data:")) dataLines.push(trimmed.slice(5));
  }

  const pending: T[] = [];
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() ?? "";
      for (const line of lines) processLine(line);
      for (const item of pending) yield item;
      pending.length = 0;
      if (trailerError) throw trailerError;
    }
    if (buffer) processLine(buffer);
    processLine("");
    for (const item of pending) yield item;
    if (trailerError) throw trailerError;
  } finally {
    reader.cancel().catch(() => {});
  }
}

export class TestServiceAIPClient implements Client<typeof pb.TestService> {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private readonly fetch: typeof fetch;
  private readonly registry: Registry;

  constructor(baseUrl: string, options: AIPClientOptions) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.headers = options.headers ?? {};
    this.fetch = options.fetch ?? globalThis.fetch;
    this.registry = options.registry;
  }

  async createResource(
    request: pb.CreateResourceRequest | MessageInitShape<typeof pb.CreateResourceRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.CreateResourceResponse> {
    const msg = create(pb.CreateResourceRequestSchema, request as MessageInitShape<typeof pb.CreateResourceRequestSchema>);
    const url = `${this.baseUrl}/v1/resources`;

    const response = await this.fetch(url, {
      method: "POST",
      headers: {
        ...this.headers,
        ...options.headers,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(toJson(pb.CreateResourceRequestSchema, msg, { registry: this.registry })),
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.CreateResourceResponseSchema, data, this.registry);
  }

  async getResource(
    request: pb.GetResourceRequest | MessageInitShape<typeof pb.GetResourceRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.GetResourceResponse> {
    const msg = create(pb.GetResourceRequestSchema, request as MessageInitShape<typeof pb.GetResourceRequestSchema>);
    let url = `${this.baseUrl}/v1/resources/{name}`;
    url = url.replace("{name}", (request.name ?? "").replace("resources/", ""));

    const params = new URLSearchParams();
    const queryString = params.toString();
    const finalUrl = queryString ? `${url}?${queryString}` : url;

    const response = await this.fetch(finalUrl, {
      method: "GET",
      headers: {
        ...this.headers,
        ...options.headers,
        Accept: "application/json",
      },
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.GetResourceResponseSchema, data, this.registry);
  }

  async updateResource(
    request: pb.UpdateResourceRequest | MessageInitShape<typeof pb.UpdateResourceRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.UpdateResourceResponse> {
    const msg = create(pb.UpdateResourceRequestSchema, request as MessageInitShape<typeof pb.UpdateResourceRequestSchema>);
    let url = `${this.baseUrl}/v1/resources/{name}`;
    url = url.replace("{name}", (request.resource?.name ?? "").replace("resources/", ""));

    const response = await this.fetch(url, {
      method: "PATCH",
      headers: {
        ...this.headers,
        ...options.headers,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(toJson(pb.UpdateResourceRequestSchema, msg, { registry: this.registry })),
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.UpdateResourceResponseSchema, data, this.registry);
  }

  async listResources(
    request: pb.ListResourcesRequest | MessageInitShape<typeof pb.ListResourcesRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.ListResourcesResponse> {
    const msg = create(pb.ListResourcesRequestSchema, request as MessageInitShape<typeof pb.ListResourcesRequestSchema>);
    const url = `${this.baseUrl}/v1/resources`;

    const params = new URLSearchParams();
    if (request.pageSize !== 0 && request.pageSize !== undefined) params.set("pageSize", String(request.pageSize));
    if (request.pageToken) params.set("pageToken", request.pageToken);
    if (request.filter) params.set("filter", request.filter);
    if (request.orderBy) params.set("orderBy", request.orderBy);
    const queryString = params.toString();
    const finalUrl = queryString ? `${url}?${queryString}` : url;

    const response = await this.fetch(finalUrl, {
      method: "GET",
      headers: {
        ...this.headers,
        ...options.headers,
        Accept: "application/json",
      },
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.ListResourcesResponseSchema, data, this.registry);
  }

  async listVersions(
    request: pb.ListVersionsRequest | MessageInitShape<typeof pb.ListVersionsRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.ListVersionsResponse> {
    const msg = create(pb.ListVersionsRequestSchema, request as MessageInitShape<typeof pb.ListVersionsRequestSchema>);
    let url = `${this.baseUrl}/v1/resources/{name}/versions`;
    url = url.replace("{name}", (request.name ?? "").replace("resources/", ""));

    const params = new URLSearchParams();
    if (request.pageToken) params.set("pageToken", request.pageToken);
    const queryString = params.toString();
    const finalUrl = queryString ? `${url}?${queryString}` : url;

    const response = await this.fetch(finalUrl, {
      method: "GET",
      headers: {
        ...this.headers,
        ...options.headers,
        Accept: "application/json",
      },
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.ListVersionsResponseSchema, data, this.registry);
  }

  async *streamResources(
    request: pb.CreateResourceRequest | MessageInitShape<typeof pb.CreateResourceRequestSchema>,
    options: CallOptions = {},
  ): AsyncGenerator<pb.CreateResourceResponse> {
    const msg = create(pb.CreateResourceRequestSchema, request as MessageInitShape<typeof pb.CreateResourceRequestSchema>);
    const url = `${this.baseUrl}/v1/resources:stream`;
    yield* streamSSE(
      this.fetch,
      url,
      "/connectaip.test.v1.TestService/StreamResources",
      toJson(pb.CreateResourceRequestSchema, msg, { registry: this.registry }),
      { ...this.headers, ...options.headers },
      options.signal,
      (data) => fromJson(pb.CreateResourceResponseSchema, JSON.parse(data), { registry: this.registry }),
    );
  }

  async deleteResource(
    request: pb.DeleteResourceRequest | MessageInitShape<typeof pb.DeleteResourceRequestSchema>,
    options: CallOptions = {},
  ): Promise<Empty> {
    const msg = create(pb.DeleteResourceRequestSchema, request as MessageInitShape<typeof pb.DeleteResourceRequestSchema>);
    let url = `${this.baseUrl}/v1/resources/{name}`;
    url = url.replace("{name}", (request.name ?? "").replace("resources/", ""));

    const params = new URLSearchParams();
    const queryString = params.toString();
    const finalUrl = queryString ? `${url}?${queryString}` : url;

    const response = await this.fetch(finalUrl, {
      method: "DELETE",
      headers: {
        ...this.headers,
        ...options.headers,
        Accept: "application/json",
      },
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(EmptySchema, data, this.registry);
  }

}

// MixedCoverageService has RPCs without HTTP rules; this AIP client only covers
// the AIP-routable subset, so it does not implement Client<typeof pb.MixedCoverageService>.
export class MixedCoverageServiceAIPClient {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private readonly fetch: typeof fetch;
  private readonly registry: Registry;

  constructor(baseUrl: string, options: AIPClientOptions) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.headers = options.headers ?? {};
    this.fetch = options.fetch ?? globalThis.fetch;
    this.registry = options.registry;
  }

  async annotatedMethod(
    request: pb.GetResourceRequest | MessageInitShape<typeof pb.GetResourceRequestSchema>,
    options: CallOptions = {},
  ): Promise<pb.GetResourceResponse> {
    const msg = create(pb.GetResourceRequestSchema, request as MessageInitShape<typeof pb.GetResourceRequestSchema>);
    let url = `${this.baseUrl}/v1/mixed/resources/{name}`;
    url = url.replace("{name}", (request.name ?? "").replace("resources/", ""));

    const params = new URLSearchParams();
    const queryString = params.toString();
    const finalUrl = queryString ? `${url}?${queryString}` : url;

    const response = await this.fetch(finalUrl, {
      method: "GET",
      headers: {
        ...this.headers,
        ...options.headers,
        Accept: "application/json",
      },
      signal: options.signal,
    });

    if (!response.ok) {
      throw await parseErrorResponse(response);
    }

    const data = await response.json();
    return fromJsonAny(pb.GetResourceResponseSchema, data, this.registry);
  }

}

