// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: test.proto

package testv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testv1 "github.com/firetiger-oss/connect-aip/internal/testproto/testv1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestServiceName is the fully-qualified name of the TestService service.
	TestServiceName = "connectaip.test.v1.TestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestServiceCreateResourceProcedure is the fully-qualified name of the TestService's
	// CreateResource RPC.
	TestServiceCreateResourceProcedure = "/connectaip.test.v1.TestService/CreateResource"
	// TestServiceGetResourceProcedure is the fully-qualified name of the TestService's GetResource RPC.
	TestServiceGetResourceProcedure = "/connectaip.test.v1.TestService/GetResource"
	// TestServiceUpdateResourceProcedure is the fully-qualified name of the TestService's
	// UpdateResource RPC.
	TestServiceUpdateResourceProcedure = "/connectaip.test.v1.TestService/UpdateResource"
	// TestServiceListResourcesProcedure is the fully-qualified name of the TestService's ListResources
	// RPC.
	TestServiceListResourcesProcedure = "/connectaip.test.v1.TestService/ListResources"
	// TestServiceListVersionsProcedure is the fully-qualified name of the TestService's ListVersions
	// RPC.
	TestServiceListVersionsProcedure = "/connectaip.test.v1.TestService/ListVersions"
	// TestServiceStreamResourcesProcedure is the fully-qualified name of the TestService's
	// StreamResources RPC.
	TestServiceStreamResourcesProcedure = "/connectaip.test.v1.TestService/StreamResources"
	// TestServiceDeleteResourceProcedure is the fully-qualified name of the TestService's
	// DeleteResource RPC.
	TestServiceDeleteResourceProcedure = "/connectaip.test.v1.TestService/DeleteResource"
)

// TestServiceClient is a client for the connectaip.test.v1.TestService service.
type TestServiceClient interface {
	CreateResource(context.Context, *connect.Request[testv1.CreateResourceRequest]) (*connect.Response[testv1.CreateResourceResponse], error)
	GetResource(context.Context, *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error)
	UpdateResource(context.Context, *connect.Request[testv1.UpdateResourceRequest]) (*connect.Response[testv1.UpdateResourceResponse], error)
	ListResources(context.Context, *connect.Request[testv1.ListResourcesRequest]) (*connect.Response[testv1.ListResourcesResponse], error)
	ListVersions(context.Context, *connect.Request[testv1.ListVersionsRequest]) (*connect.Response[testv1.ListVersionsResponse], error)
	// Server-streaming method used to validate the SSE handler path.
	StreamResources(context.Context, *connect.Request[testv1.CreateResourceRequest]) (*connect.ServerStreamForClient[testv1.CreateResourceResponse], error)
	// Returns google.protobuf.Empty to exercise cross-package response types.
	DeleteResource(context.Context, *connect.Request[testv1.DeleteResourceRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewTestServiceClient constructs a client for the connectaip.test.v1.TestService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testServiceMethods := testv1.File_test_proto.Services().ByName("TestService").Methods()
	return &testServiceClient{
		createResource: connect.NewClient[testv1.CreateResourceRequest, testv1.CreateResourceResponse](
			httpClient,
			baseURL+TestServiceCreateResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("CreateResource")),
			connect.WithClientOptions(opts...),
		),
		getResource: connect.NewClient[testv1.GetResourceRequest, testv1.GetResourceResponse](
			httpClient,
			baseURL+TestServiceGetResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
		updateResource: connect.NewClient[testv1.UpdateResourceRequest, testv1.UpdateResourceResponse](
			httpClient,
			baseURL+TestServiceUpdateResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("UpdateResource")),
			connect.WithClientOptions(opts...),
		),
		listResources: connect.NewClient[testv1.ListResourcesRequest, testv1.ListResourcesResponse](
			httpClient,
			baseURL+TestServiceListResourcesProcedure,
			connect.WithSchema(testServiceMethods.ByName("ListResources")),
			connect.WithClientOptions(opts...),
		),
		listVersions: connect.NewClient[testv1.ListVersionsRequest, testv1.ListVersionsResponse](
			httpClient,
			baseURL+TestServiceListVersionsProcedure,
			connect.WithSchema(testServiceMethods.ByName("ListVersions")),
			connect.WithClientOptions(opts...),
		),
		streamResources: connect.NewClient[testv1.CreateResourceRequest, testv1.CreateResourceResponse](
			httpClient,
			baseURL+TestServiceStreamResourcesProcedure,
			connect.WithSchema(testServiceMethods.ByName("StreamResources")),
			connect.WithClientOptions(opts...),
		),
		deleteResource: connect.NewClient[testv1.DeleteResourceRequest, emptypb.Empty](
			httpClient,
			baseURL+TestServiceDeleteResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("DeleteResource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testServiceClient implements TestServiceClient.
type testServiceClient struct {
	createResource  *connect.Client[testv1.CreateResourceRequest, testv1.CreateResourceResponse]
	getResource     *connect.Client[testv1.GetResourceRequest, testv1.GetResourceResponse]
	updateResource  *connect.Client[testv1.UpdateResourceRequest, testv1.UpdateResourceResponse]
	listResources   *connect.Client[testv1.ListResourcesRequest, testv1.ListResourcesResponse]
	listVersions    *connect.Client[testv1.ListVersionsRequest, testv1.ListVersionsResponse]
	streamResources *connect.Client[testv1.CreateResourceRequest, testv1.CreateResourceResponse]
	deleteResource  *connect.Client[testv1.DeleteResourceRequest, emptypb.Empty]
}

// CreateResource calls connectaip.test.v1.TestService.CreateResource.
func (c *testServiceClient) CreateResource(ctx context.Context, req *connect.Request[testv1.CreateResourceRequest]) (*connect.Response[testv1.CreateResourceResponse], error) {
	return c.createResource.CallUnary(ctx, req)
}

// GetResource calls connectaip.test.v1.TestService.GetResource.
func (c *testServiceClient) GetResource(ctx context.Context, req *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error) {
	return c.getResource.CallUnary(ctx, req)
}

// UpdateResource calls connectaip.test.v1.TestService.UpdateResource.
func (c *testServiceClient) UpdateResource(ctx context.Context, req *connect.Request[testv1.UpdateResourceRequest]) (*connect.Response[testv1.UpdateResourceResponse], error) {
	return c.updateResource.CallUnary(ctx, req)
}

// ListResources calls connectaip.test.v1.TestService.ListResources.
func (c *testServiceClient) ListResources(ctx context.Context, req *connect.Request[testv1.ListResourcesRequest]) (*connect.Response[testv1.ListResourcesResponse], error) {
	return c.listResources.CallUnary(ctx, req)
}

// ListVersions calls connectaip.test.v1.TestService.ListVersions.
func (c *testServiceClient) ListVersions(ctx context.Context, req *connect.Request[testv1.ListVersionsRequest]) (*connect.Response[testv1.ListVersionsResponse], error) {
	return c.listVersions.CallUnary(ctx, req)
}

// StreamResources calls connectaip.test.v1.TestService.StreamResources.
func (c *testServiceClient) StreamResources(ctx context.Context, req *connect.Request[testv1.CreateResourceRequest]) (*connect.ServerStreamForClient[testv1.CreateResourceResponse], error) {
	return c.streamResources.CallServerStream(ctx, req)
}

// DeleteResource calls connectaip.test.v1.TestService.DeleteResource.
func (c *testServiceClient) DeleteResource(ctx context.Context, req *connect.Request[testv1.DeleteResourceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteResource.CallUnary(ctx, req)
}

// TestServiceHandler is an implementation of the connectaip.test.v1.TestService service.
type TestServiceHandler interface {
	CreateResource(context.Context, *connect.Request[testv1.CreateResourceRequest]) (*connect.Response[testv1.CreateResourceResponse], error)
	GetResource(context.Context, *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error)
	UpdateResource(context.Context, *connect.Request[testv1.UpdateResourceRequest]) (*connect.Response[testv1.UpdateResourceResponse], error)
	ListResources(context.Context, *connect.Request[testv1.ListResourcesRequest]) (*connect.Response[testv1.ListResourcesResponse], error)
	ListVersions(context.Context, *connect.Request[testv1.ListVersionsRequest]) (*connect.Response[testv1.ListVersionsResponse], error)
	// Server-streaming method used to validate the SSE handler path.
	StreamResources(context.Context, *connect.Request[testv1.CreateResourceRequest], *connect.ServerStream[testv1.CreateResourceResponse]) error
	// Returns google.protobuf.Empty to exercise cross-package response types.
	DeleteResource(context.Context, *connect.Request[testv1.DeleteResourceRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewTestServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestServiceHandler(svc TestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testServiceMethods := testv1.File_test_proto.Services().ByName("TestService").Methods()
	testServiceCreateResourceHandler := connect.NewUnaryHandler(
		TestServiceCreateResourceProcedure,
		svc.CreateResource,
		connect.WithSchema(testServiceMethods.ByName("CreateResource")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceGetResourceHandler := connect.NewUnaryHandler(
		TestServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(testServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceUpdateResourceHandler := connect.NewUnaryHandler(
		TestServiceUpdateResourceProcedure,
		svc.UpdateResource,
		connect.WithSchema(testServiceMethods.ByName("UpdateResource")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceListResourcesHandler := connect.NewUnaryHandler(
		TestServiceListResourcesProcedure,
		svc.ListResources,
		connect.WithSchema(testServiceMethods.ByName("ListResources")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceListVersionsHandler := connect.NewUnaryHandler(
		TestServiceListVersionsProcedure,
		svc.ListVersions,
		connect.WithSchema(testServiceMethods.ByName("ListVersions")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceStreamResourcesHandler := connect.NewServerStreamHandler(
		TestServiceStreamResourcesProcedure,
		svc.StreamResources,
		connect.WithSchema(testServiceMethods.ByName("StreamResources")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceDeleteResourceHandler := connect.NewUnaryHandler(
		TestServiceDeleteResourceProcedure,
		svc.DeleteResource,
		connect.WithSchema(testServiceMethods.ByName("DeleteResource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/connectaip.test.v1.TestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestServiceCreateResourceProcedure:
			testServiceCreateResourceHandler.ServeHTTP(w, r)
		case TestServiceGetResourceProcedure:
			testServiceGetResourceHandler.ServeHTTP(w, r)
		case TestServiceUpdateResourceProcedure:
			testServiceUpdateResourceHandler.ServeHTTP(w, r)
		case TestServiceListResourcesProcedure:
			testServiceListResourcesHandler.ServeHTTP(w, r)
		case TestServiceListVersionsProcedure:
			testServiceListVersionsHandler.ServeHTTP(w, r)
		case TestServiceStreamResourcesProcedure:
			testServiceStreamResourcesHandler.ServeHTTP(w, r)
		case TestServiceDeleteResourceProcedure:
			testServiceDeleteResourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestServiceHandler struct{}

func (UnimplementedTestServiceHandler) CreateResource(context.Context, *connect.Request[testv1.CreateResourceRequest]) (*connect.Response[testv1.CreateResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.CreateResource is not implemented"))
}

func (UnimplementedTestServiceHandler) GetResource(context.Context, *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.GetResource is not implemented"))
}

func (UnimplementedTestServiceHandler) UpdateResource(context.Context, *connect.Request[testv1.UpdateResourceRequest]) (*connect.Response[testv1.UpdateResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.UpdateResource is not implemented"))
}

func (UnimplementedTestServiceHandler) ListResources(context.Context, *connect.Request[testv1.ListResourcesRequest]) (*connect.Response[testv1.ListResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.ListResources is not implemented"))
}

func (UnimplementedTestServiceHandler) ListVersions(context.Context, *connect.Request[testv1.ListVersionsRequest]) (*connect.Response[testv1.ListVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.ListVersions is not implemented"))
}

func (UnimplementedTestServiceHandler) StreamResources(context.Context, *connect.Request[testv1.CreateResourceRequest], *connect.ServerStream[testv1.CreateResourceResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.StreamResources is not implemented"))
}

func (UnimplementedTestServiceHandler) DeleteResource(context.Context, *connect.Request[testv1.DeleteResourceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connectaip.test.v1.TestService.DeleteResource is not implemented"))
}
