// Code generated by protoc-gen-aip-go. DO NOT EDIT.

package testv1connect

import (
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

import (
	"context"
	"fmt"
	"iter"
	"net/http"

	"connectrpc.com/connect"
	connectaip "github.com/firetiger-oss/connect-aip"
	testv1 "github.com/firetiger-oss/connect-aip/internal/testproto/testv1"
	connectsse "github.com/firetiger-oss/connect-sse"
)

// NewTestServiceAIPHandler returns an iterator of (pattern, handler) pairs
// for registering AIP routes with http.ServeMux using Go 1.22+ patterns.
// Usage:
//
//	for pattern, handler := range NewTestServiceAIPHandler(svc, opts...) {
//	    mux.Handle(pattern, handler)
//	}
func NewTestServiceAIPHandler(
	svc TestServiceHandler,
	opts ...connect.HandlerOption,
) iter.Seq2[string, http.Handler] {
	opts = append(opts, connect.WithCompression("gzip", nil, nil))
	_, connectHandler := NewTestServiceHandler(svc, opts...)

	return func(yield func(string, http.Handler) bool) {
		if !yield("POST /v1/resources", handleTestServiceCreateResource(connectHandler)) {
			return
		}
		if !yield("GET /v1/resources/{name}", handleTestServiceGetResource(connectHandler)) {
			return
		}
		if !yield("PATCH /v1/resources/{name}", handleTestServiceUpdateResource(connectHandler)) {
			return
		}
		if !yield("GET /v1/resources", handleTestServiceListResources(connectHandler)) {
			return
		}
		if !yield("GET /v1/resources/{name}/versions", handleTestServiceListVersions(connectHandler)) {
			return
		}
		if !yield("POST /v1/resources:stream", handleTestServiceStreamResources(connectHandler)) {
			return
		}
		if !yield("DELETE /v1/resources/{name}", handleTestServiceDeleteResource(connectHandler)) {
			return
		}
	}
}

func handleTestServiceCreateResource(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.Forward[*testv1.CreateResourceRequest, *testv1.CreateResourceResponse](w, req, TestServiceCreateResourceProcedure, connectHandler)
	})
}

func handleTestServiceGetResource(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithBody[*testv1.GetResourceRequest, *testv1.GetResourceResponse](w, req, TestServiceGetResourceProcedure, connectHandler, &testv1.GetResourceRequest{Name: "resources/" + req.PathValue("name")})
	})
}

func handleTestServiceUpdateResource(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithPathVars[*testv1.UpdateResourceRequest, *testv1.UpdateResourceResponse](w, req, TestServiceUpdateResourceProcedure, connectHandler, &testv1.UpdateResourceRequest{Resource: &testv1.Resource{Name: "resources/" + req.PathValue("name")}})
	})
}

func handleTestServiceListResources(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithBody[*testv1.ListResourcesRequest, *testv1.ListResourcesResponse](w, req, TestServiceListResourcesProcedure, connectHandler, &testv1.ListResourcesRequest{})
	})
}

func handleTestServiceListVersions(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithBody[*testv1.ListVersionsRequest, *testv1.ListVersionsResponse](w, req, TestServiceListVersionsProcedure, connectHandler, &testv1.ListVersionsRequest{Name: "resources/" + req.PathValue("name")})
	})
}

func handleTestServiceStreamResources(connectHandler http.Handler) http.Handler {
	return &connectsse.Server{Handler: connectHandler}
}

func handleTestServiceDeleteResource(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithBody[*testv1.DeleteResourceRequest, *emptypb.Empty](w, req, TestServiceDeleteResourceProcedure, connectHandler, &testv1.DeleteResourceRequest{Name: "resources/" + req.PathValue("name")})
	})
}

// TestServiceAIPClient is an alias for the standard TestServiceClient interface.
// All RPCs on TestService have HTTP rules, so the AIP client is a
// drop-in replacement for TestServiceClient; this alias is kept for
// backwards compatibility with code that types variables as TestServiceAIPClient.
type TestServiceAIPClient = TestServiceClient

type testServiceAIPClient struct {
	createResource  *connectaip.Client[testv1.CreateResourceRequest, testv1.CreateResourceResponse]
	getResource     *connectaip.Client[testv1.GetResourceRequest, testv1.GetResourceResponse]
	updateResource  *connectaip.Client[testv1.UpdateResourceRequest, testv1.UpdateResourceResponse]
	listResources   *connectaip.Client[testv1.ListResourcesRequest, testv1.ListResourcesResponse]
	listVersions    *connectaip.Client[testv1.ListVersionsRequest, testv1.ListVersionsResponse]
	streamResources *connect.Client[testv1.CreateResourceRequest, testv1.CreateResourceResponse]
	deleteResource  *connectaip.Client[testv1.DeleteResourceRequest, emptypb.Empty]
}

// NewTestServiceAIPClient creates a new AIP client for TestService.
// The returned client satisfies the standard TestServiceClient interface,
// so it can be used as a drop-in replacement for NewTestServiceClient.
func NewTestServiceAIPClient(httpClient connect.HTTPClient, baseURL string, opts ...connectaip.ClientOption) TestServiceClient {
	return &testServiceAIPClient{
		createResource: connectaip.NewClient[testv1.CreateResourceRequest, testv1.CreateResourceResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "POST",
				URLPattern: "/v1/resources",
				Procedure:  TestServiceCreateResourceProcedure,
			},
			nil,
			nil,
			opts...,
		),
		getResource: connectaip.NewClient[testv1.GetResourceRequest, testv1.GetResourceResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "GET",
				URLPattern: "/v1/resources/{name}",
				Procedure:  TestServiceGetResourceProcedure,
				PathVars: []connectaip.PathVar{
					{Placeholder: "{name}", Prefix: "resources/"},
				},
			},
			TestServiceGetResourcePathVars,
			func(*testv1.GetResourceRequest) map[string]string { return nil },
			opts...,
		),
		updateResource: connectaip.NewClient[testv1.UpdateResourceRequest, testv1.UpdateResourceResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "PATCH",
				URLPattern: "/v1/resources/{name}",
				Procedure:  TestServiceUpdateResourceProcedure,
				PathVars: []connectaip.PathVar{
					{Placeholder: "{name}", Prefix: "resources/"},
				},
			},
			TestServiceUpdateResourcePathVars,
			nil,
			opts...,
		),
		listResources: connectaip.NewClient[testv1.ListResourcesRequest, testv1.ListResourcesResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "GET",
				URLPattern: "/v1/resources",
				Procedure:  TestServiceListResourcesProcedure,
			},
			nil,
			TestServiceListResourcesQuery,
			opts...,
		),
		listVersions: connectaip.NewClient[testv1.ListVersionsRequest, testv1.ListVersionsResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "GET",
				URLPattern: "/v1/resources/{name}/versions",
				Procedure:  TestServiceListVersionsProcedure,
				PathVars: []connectaip.PathVar{
					{Placeholder: "{name}", Prefix: "resources/"},
				},
			},
			TestServiceListVersionsPathVars,
			TestServiceListVersionsQuery,
			opts...,
		),
		streamResources: connect.NewClient[testv1.CreateResourceRequest, testv1.CreateResourceResponse](
			connectaip.NewSSEClient(httpClient, baseURL+"/v1/resources:stream", nil, opts...),
			connectaip.SSEProcedureURL(baseURL, TestServiceStreamResourcesProcedure),
			connect.WithProtoJSON(),
		),
		deleteResource: connectaip.NewClient[testv1.DeleteResourceRequest, emptypb.Empty](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "DELETE",
				URLPattern: "/v1/resources/{name}",
				Procedure:  TestServiceDeleteResourceProcedure,
				PathVars: []connectaip.PathVar{
					{Placeholder: "{name}", Prefix: "resources/"},
				},
			},
			TestServiceDeleteResourcePathVars,
			func(*testv1.DeleteResourceRequest) map[string]string { return nil },
			opts...,
		),
	}
}

func TestServiceGetResourcePathVars(req *testv1.GetResourceRequest) map[string]string {
	return map[string]string{
		"{name}": req.GetName(),
	}
}

func TestServiceUpdateResourcePathVars(req *testv1.UpdateResourceRequest) map[string]string {
	return map[string]string{
		"{name}": req.GetResource().GetName(),
	}
}

func TestServiceListVersionsPathVars(req *testv1.ListVersionsRequest) map[string]string {
	return map[string]string{
		"{name}": req.GetName(),
	}
}

func TestServiceDeleteResourcePathVars(req *testv1.DeleteResourceRequest) map[string]string {
	return map[string]string{
		"{name}": req.GetName(),
	}
}

func TestServiceListResourcesQuery(req *testv1.ListResourcesRequest) map[string]string {
	result := make(map[string]string)
	if v := req.GetPageSize(); v != 0 {
		result["pageSize"] = fmt.Sprint(v)
	}
	if v := req.GetPageToken(); v != "" {
		result["pageToken"] = v
	}
	if v := req.GetFilter(); v != "" {
		result["filter"] = v
	}
	if v := req.GetOrderBy(); v != "" {
		result["orderBy"] = v
	}
	return result
}

func TestServiceListVersionsQuery(req *testv1.ListVersionsRequest) map[string]string {
	result := make(map[string]string)
	if v := req.GetPageToken(); v != "" {
		result["pageToken"] = v
	}
	return result
}

func (c *testServiceAIPClient) CreateResource(ctx context.Context, req *connect.Request[testv1.CreateResourceRequest]) (*connect.Response[testv1.CreateResourceResponse], error) {
	return c.createResource.CallRequest(ctx, req)
}

func (c *testServiceAIPClient) GetResource(ctx context.Context, req *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error) {
	return c.getResource.CallRequest(ctx, req)
}

func (c *testServiceAIPClient) UpdateResource(ctx context.Context, req *connect.Request[testv1.UpdateResourceRequest]) (*connect.Response[testv1.UpdateResourceResponse], error) {
	return c.updateResource.CallRequest(ctx, req)
}

func (c *testServiceAIPClient) ListResources(ctx context.Context, req *connect.Request[testv1.ListResourcesRequest]) (*connect.Response[testv1.ListResourcesResponse], error) {
	return c.listResources.CallRequest(ctx, req)
}

func (c *testServiceAIPClient) ListVersions(ctx context.Context, req *connect.Request[testv1.ListVersionsRequest]) (*connect.Response[testv1.ListVersionsResponse], error) {
	return c.listVersions.CallRequest(ctx, req)
}

func (c *testServiceAIPClient) StreamResources(ctx context.Context, req *connect.Request[testv1.CreateResourceRequest]) (*connect.ServerStreamForClient[testv1.CreateResourceResponse], error) {
	return c.streamResources.CallServerStream(ctx, req)
}

func (c *testServiceAIPClient) DeleteResource(ctx context.Context, req *connect.Request[testv1.DeleteResourceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteResource.CallRequest(ctx, req)
}

// NewMixedCoverageServiceAIPHandler returns an iterator of (pattern, handler) pairs
// for registering AIP routes with http.ServeMux using Go 1.22+ patterns.
// Usage:
//
//	for pattern, handler := range NewMixedCoverageServiceAIPHandler(svc, opts...) {
//	    mux.Handle(pattern, handler)
//	}
func NewMixedCoverageServiceAIPHandler(
	svc MixedCoverageServiceHandler,
	opts ...connect.HandlerOption,
) iter.Seq2[string, http.Handler] {
	_, connectHandler := NewMixedCoverageServiceHandler(svc, opts...)

	return func(yield func(string, http.Handler) bool) {
		if !yield("GET /v1/mixed/resources/{name}", handleMixedCoverageServiceAnnotatedMethod(connectHandler)) {
			return
		}
	}
}

func handleMixedCoverageServiceAnnotatedMethod(connectHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		connectaip.ForwardWithBody[*testv1.GetResourceRequest, *testv1.GetResourceResponse](w, req, MixedCoverageServiceAnnotatedMethodProcedure, connectHandler, &testv1.GetResourceRequest{Name: "resources/" + req.PathValue("name")})
	})
}

// MixedCoverageServiceAIPClient is an AIP client for MixedCoverageService.
// MixedCoverageService has RPCs without HTTP rules; use the connect-go-generated
// MixedCoverageServiceClient (via NewMixedCoverageServiceClient) for full coverage.
type MixedCoverageServiceAIPClient interface {
	AnnotatedMethod(ctx context.Context, req *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error)
}

type mixedCoverageServiceAIPClient struct {
	annotatedMethod *connectaip.Client[testv1.GetResourceRequest, testv1.GetResourceResponse]
}

// NewMixedCoverageServiceAIPClient creates a new AIP client for MixedCoverageService.
func NewMixedCoverageServiceAIPClient(httpClient connect.HTTPClient, baseURL string, opts ...connectaip.ClientOption) MixedCoverageServiceAIPClient {
	return &mixedCoverageServiceAIPClient{
		annotatedMethod: connectaip.NewClient[testv1.GetResourceRequest, testv1.GetResourceResponse](
			httpClient, baseURL,
			connectaip.MethodSpec{
				HTTPMethod: "GET",
				URLPattern: "/v1/mixed/resources/{name}",
				Procedure:  MixedCoverageServiceAnnotatedMethodProcedure,
				PathVars: []connectaip.PathVar{
					{Placeholder: "{name}", Prefix: "resources/"},
				},
			},
			MixedCoverageServiceAnnotatedMethodPathVars,
			func(*testv1.GetResourceRequest) map[string]string { return nil },
			opts...,
		),
	}
}

func MixedCoverageServiceAnnotatedMethodPathVars(req *testv1.GetResourceRequest) map[string]string {
	return map[string]string{
		"{name}": req.GetName(),
	}
}

func (c *mixedCoverageServiceAIPClient) AnnotatedMethod(ctx context.Context, req *connect.Request[testv1.GetResourceRequest]) (*connect.Response[testv1.GetResourceResponse], error) {
	return c.annotatedMethod.CallRequest(ctx, req)
}
