// protoc-gen-aip-go generates AIP-shaped REST/HTTP handlers and clients for
// ConnectRPC services. It reads google.api.http annotations from proto files
// and generates Go code that routes HTTP requests to the appropriate
// ConnectRPC handlers, following Google AIP-127 (HTTP transcoding) and AIP-130
// (resource-collection paths) conventions.
//
// Usage with buf:
//
//	plugins:
//	  - local: protoc-gen-aip-go
//	    out: proto/go
//	    opt:
//	      - paths=source_relative
//	    strategy: all
package main

import (
	"flag"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

// serveMuxVarRE matches a single ServeMux path variable placeholder,
// e.g. "{name}" or "{name...}".
var serveMuxVarRE = regexp.MustCompile(`\{[^{}]+}`)

func main() {
	var flags flag.FlagSet

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

// generateFile generates AIP handler code for a single proto file.
func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	// Count how many services will have usable routes after all filtering
	var totalUsableRoutes int
	for _, service := range file.Services {
		totalUsableRoutes += countUsableRoutes(service)
	}

	if totalUsableRoutes == 0 {
		return
	}

	connectPkgName := string(file.GoPackageName) + "connect"
	connectImportPath := protogen.GoImportPath(string(file.GoImportPath) + "/" + connectPkgName)

	prefix := file.GeneratedFilenamePrefix
	lastSlash := strings.LastIndex(prefix, "/")
	var dir, baseName string
	if lastSlash >= 0 {
		dir = prefix[:lastSlash+1]
		baseName = prefix[lastSlash+1:]
	} else {
		dir = ""
		baseName = prefix
	}
	filename := dir + connectPkgName + "/" + baseName + "_aip.connect.go"
	g := gen.NewGeneratedFile(filename, connectImportPath)

	g.P("// Code generated by protoc-gen-aip-go. DO NOT EDIT.")
	g.P()
	g.P("package ", connectPkgName)
	g.P()

	generateImports(g, file, fileNeedsFmt(file), fileNeedsStrings(file), fileNeedsConnectSSE(file), fileNeedsEncodingJSON(file))

	alias := protoPackageAlias(file)
	protoImportPath := string(file.GoImportPath)
	for _, service := range file.Services {
		generateServiceHandler(g, service, alias, protoImportPath)
		generateServiceClient(g, service, alias, protoImportPath)
	}
}

// countUsableRoutes counts how many routes in a service will be usable after all filtering.
func countUsableRoutes(service *protogen.Service) int {
	var count int
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue // Skip client-streaming and bidirectional methods
		}
		httpRule := getHTTPRule(method)
		if httpRule == nil {
			continue
		}
		route := parseHTTPRule(method, httpRule)
		if route == nil {
			continue
		}
		if !hasOnlyStringPathParams(route, method.Input) {
			continue
		}
		count++
	}
	return count
}

// protoPackageAlias returns the import alias for the proto package.
// This is used to reference proto message types in generated code.
func protoPackageAlias(file *protogen.File) string {
	return string(file.GoPackageName)
}

// generateImports generates the import block for the generated file.
func generateImports(g *protogen.GeneratedFile, file *protogen.File, needsFmt, needsStrings, needsConnectSSE, needsEncodingJSON bool) {
	protoImportPath := string(file.GoImportPath)
	alias := protoPackageAlias(file)
	g.P("import (")
	g.P("\t", `"context"`)
	if needsEncodingJSON {
		g.P("\t", `"encoding/json"`)
	}
	if needsFmt {
		g.P("\t", `"fmt"`)
	}
	g.P("\t", `"iter"`)
	g.P("\t", `"net/http"`)
	if needsStrings {
		g.P("\t", `"strings"`)
	}
	g.P()
	// Third-party imports must be emitted in alphabetical order by path so the
	// generated file passes `gofmt -l`. We collect (path, alias) pairs and sort.
	type imp struct {
		path  string
		alias string
	}
	thirdParty := []imp{
		{path: "connectrpc.com/connect"},
		{path: "github.com/firetiger-oss/connect-aip", alias: "connectaip"},
		{path: protoImportPath, alias: alias},
	}
	if needsConnectSSE {
		thirdParty = append(thirdParty, imp{path: "github.com/firetiger-oss/connect-sse", alias: "connectsse"})
	}
	sort.Slice(thirdParty, func(i, j int) bool { return thirdParty[i].path < thirdParty[j].path })
	for _, i := range thirdParty {
		if i.alias == "" {
			g.P("\t", `"`, i.path, `"`)
		} else {
			g.P("\t", i.alias, ` "`, i.path, `"`)
		}
	}
	g.P(")")
	g.P()
}

// fileNeedsFmt checks if any service in the file will generate code that uses fmt.Sprint.
func fileNeedsFmt(file *protogen.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil {
				continue
			}
			if !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			// Check if this is a GET/DELETE or empty-body route with numeric query params
			if (route.method == "GET" || route.method == "DELETE" || route.bodyField == "") && hasNumericQueryParams(route) {
				return true
			}
		}
	}
	return false
}

// fileNeedsStrings checks if any service in the file will generate code that uses the strings package.
// This is needed for dispatcher handlers that use strings.HasSuffix and for TrimSuffix in path vars,
// and for SSE path-var extractor functions that strip resource name prefixes.
func fileNeedsStrings(file *protogen.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil {
				continue
			}
			if !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			// Check if this route has a custom verb (unary handler uses strings.HasSuffix)
			if route.customVerb != "" {
				return true
			}
			// Streaming routes with prefixed path vars need strings.TrimPrefix
			if method.Desc.IsStreamingServer() {
				for _, pv := range route.pathVars {
					if pv.prefix != "" {
						return true
					}
				}
			}
		}
	}
	return false
}

// fileNeedsEncodingJSON checks if any service in the file has server-streaming routes with path
// variables, which require encoding/json to unmarshal the SSE message for path substitution.
func fileNeedsEncodingJSON(file *protogen.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || !method.Desc.IsStreamingServer() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil || !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			if len(route.pathVars) > 0 {
				return true
			}
		}
	}
	return false
}

// fileNeedsConnectSSE checks if any service in the file has server-streaming methods with AIP routes.
// When true, the generated file must import github.com/firetiger-oss/connect-sse.
func fileNeedsConnectSSE(file *protogen.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || !method.Desc.IsStreamingServer() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil {
				continue
			}
			if !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			return true
		}
	}
	return false
}

// hasNumericQueryParams checks if a route has any numeric query parameters that need fmt.Sprint.
func hasNumericQueryParams(route *routeInfo) bool {
	pathVarFields := make(map[string]bool)
	for _, pv := range route.pathVars {
		pathVarFields[pv.fieldPath] = true
	}

	for _, field := range route.inputType.Fields {
		fieldPath := string(field.Desc.Name())
		if pathVarFields[fieldPath] {
			continue
		}
		switch field.Desc.Kind().String() {
		case "int32", "int64", "uint32", "uint64", "float", "double", "enum":
			return true
		}
	}
	return false
}

// generateServiceHandler generates the AIP handler for a service.
func generateServiceHandler(g *protogen.GeneratedFile, service *protogen.Service, pkgAlias, protoImportPath string) {
	serviceName := service.GoName
	handlerName := serviceName + "AIPHandler"

	var routes []routeInfo
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue // Skip client-streaming and bidirectional methods
		}
		httpRule := getHTTPRule(method)
		if httpRule == nil {
			continue
		}
		route := parseHTTPRule(method, httpRule)
		if route == nil {
			continue
		}
		// Skip routes with non-string path parameters
		if !hasOnlyStringPathParams(route, method.Input) {
			continue
		}
		routes = append(routes, *route)
	}

	if len(routes) == 0 {
		return
	}

	// Group routes by (method, serveMuxPath) for dispatcher generation
	groups := groupRoutesByPattern(routes)

	generateHandlerConstructorWithGroups(g, serviceName, handlerName, groups)
	generateStandaloneHandlers(g, serviceName, routes, pkgAlias, protoImportPath)
	generateDispatcherHandlers(g, serviceName, groups, pkgAlias)
}

// routeInfo holds parsed information about an HTTP route.
type routeInfo struct {
	method            string
	pattern           string
	bodyField         string
	rpcMethod         string
	inputType         *protogen.Message
	outputType        *protogen.Message
	pathVars          []pathVar
	serveMuxPath      string
	customVerb        string // Custom method verb (e.g., ":revokeVersion")
	isServerStreaming bool   // true if the RPC is server-streaming (returns stream)
}

// pathVar represents a path variable extracted from a URL pattern.
type pathVar struct {
	name       string // Sanitized name for ServeMux (no dots)
	fieldPath  string // Original field path for setting proto fields; empty for non-primary multi-wildcard vars
	prefix     string // Path prefix to prepend to the captured value (e.g., "customers/")
	wildcard   bool
	customVerb string // Custom verb suffix to strip at runtime (e.g., ":revokeVersion")

	// Multi-wildcard expansion: set when the proto pattern has multiple wildcards
	// (e.g., {name=agents/*/slos/*}). All sub-vars in a group share the same multiGroup
	// pointer; only the primary var (multiGroup.idx == 0) generates a field assignment.
	multiGroup *multiVarGroup
}

// multiVarGroup holds data for expanding a single proto field that spans multiple
// URL path wildcards (e.g., {name=agents/*/slos/*} → agents/{name_0}/slos/{name_1}).
type multiVarGroup struct {
	idx       int      // index of this var within the group (0 = primary)
	fieldPath string   // the proto field path (same for all vars in the group)
	prefix    string   // literal prefix before the first wildcard (e.g., "agents/")
	seps      []string // seps[i] = literal segment between wildcard i and wildcard i+1
	names     []string // all sub-var names in order (e.g., ["name_0", "name_1"])
	lastVerb  string   // custom verb suffix on the final wildcard (e.g., ":record")
}

// routeGroup groups routes that share the same HTTP method and ServeMux path.
// This enables dispatcher handlers for custom verb patterns.
type routeGroup struct {
	method       string
	serveMuxPath string
	baseRoute    *routeInfo   // Route without custom verb (nil if all routes have verbs)
	verbRoutes   []*routeInfo // Routes with custom verbs
}

// groupRoutesByPattern groups routes by (method, normalizedServeMuxPath).
// Routes with the same base path but different custom verbs are grouped together.
// When two routes share the same structural path but have different path variable
// names (e.g. {name...} vs {session...}), they are grouped and the verb routes'
// pathVar names are remapped to match the base route's names so that a single
// ServeMux registration suffices.
func groupRoutesByPattern(routes []routeInfo) []routeGroup {
	// Map key: "METHOD normalizedPath"
	groups := make(map[string]*routeGroup)
	var order []string // Preserve order

	for i := range routes {
		route := &routes[i]
		normalized := normalizeServeMuxPath(route.serveMuxPath)
		key := route.method + " " + normalized

		group, exists := groups[key]
		if !exists {
			group = &routeGroup{
				method:       route.method,
				serveMuxPath: route.serveMuxPath, // actual path; overridden by base route
			}
			groups[key] = group
			order = append(order, key)
		}

		if route.customVerb == "" {
			group.baseRoute = route
			group.serveMuxPath = route.serveMuxPath // base route owns the registered path
		} else {
			group.verbRoutes = append(group.verbRoutes, route)
		}
	}

	// For groups that share a structural path pattern but use different proto
	// field names for the path variable (e.g. {name=agents/*} vs
	// {agent=agents/*}:addSubscriber), remap every verb route's pathVar names
	// to a canonical set so all handlers in the group can use req.PathValue
	// with the same names that the registered mux pattern actually captures.
	// The canonical names come from the base route when present; otherwise
	// the first verb route owns the registered serveMuxPath, so its names win.
	for _, key := range order {
		group := groups[key]
		var basePVs []pathVar
		var verbsToRemap []*routeInfo
		if group.baseRoute != nil {
			basePVs = group.baseRoute.pathVars
			verbsToRemap = group.verbRoutes
		} else if len(group.verbRoutes) > 1 {
			basePVs = group.verbRoutes[0].pathVars
			verbsToRemap = group.verbRoutes[1:]
		} else {
			continue
		}
		for _, verbRoute := range verbsToRemap {
			for j := range verbRoute.pathVars {
				if j < len(basePVs) {
					newName := basePVs[j].name
					verbRoute.pathVars[j].name = newName
					// Also update the multiGroup names slice so that
					// generateNestedFieldAssignment uses the correct variable name.
					if mg := verbRoute.pathVars[j].multiGroup; mg != nil {
						mg.names[mg.idx] = newName
					}
				}
			}
		}
	}

	// Convert to slice in original order
	result := make([]routeGroup, 0, len(order))
	for _, key := range order {
		result = append(result, *groups[key])
	}
	return result
}

// normalizeServeMuxPath replaces path variable names with a canonical placeholder
// so that structurally identical patterns group together regardless of variable name.
// For example, "/v1/agents/{session...}" and "/v1/agents/{name...}" both normalize
// to "/v1/agents/{_...}" and are treated as the same registration slot.
func normalizeServeMuxPath(path string) string {
	return serveMuxVarRE.ReplaceAllStringFunc(path, func(m string) string {
		if strings.HasSuffix(m, "...}") {
			return "{_...}"
		}
		return "{_}"
	})
}

// generateHandlerConstructorWithGroups generates the constructor function that returns iter.Seq2.
// It handles route groups with custom verbs by generating dispatcher handlers.
func generateHandlerConstructorWithGroups(g *protogen.GeneratedFile, serviceName, handlerName string, groups []routeGroup) {
	g.P("// New", handlerName, " returns an iterator of (pattern, handler) pairs")
	g.P("// for registering AIP routes with http.ServeMux using Go 1.22+ patterns.")
	g.P("// Usage:")
	g.P("//")
	g.P("//\tfor pattern, handler := range New", handlerName, "(svc, opts...) {")
	g.P("//\t    mux.Handle(pattern, handler)")
	g.P("//\t}")
	hasStreaming := false
	for _, group := range groups {
		if group.baseRoute != nil && group.baseRoute.isServerStreaming {
			hasStreaming = true
			break
		}
		for _, vr := range group.verbRoutes {
			if vr.isServerStreaming {
				hasStreaming = true
				break
			}
		}
		if hasStreaming {
			break
		}
	}

	g.P("func New", handlerName, "(")
	g.P("\tsvc ", serviceName, "Handler,")
	g.P("\topts ...connect.HandlerOption,")
	g.P(") iter.Seq2[string, http.Handler] {")
	if hasStreaming {
		// connectsse.Server forwards the outer request's Accept-Encoding header to the inner
		// Connect handler. If the handler supports gzip, it compresses streaming responses,
		// but connectsse.Client cannot decompress them. Removing gzip support prevents this.
		g.P("\topts = append(opts, connect.WithCompression(\"gzip\", nil, nil))")
	}
	g.P("\t_, connectHandler := New", serviceName, "Handler(svc, opts...)")
	g.P()
	g.P("\treturn func(yield func(string, http.Handler) bool) {")

	for _, group := range groups {
		// connectsse.Client always POSTs regardless of the annotation HTTP method, and
		// connectsse.Server only reads the body — so streaming routes must be POST.
		method := group.method
		groupIsStreaming := (group.baseRoute != nil && group.baseRoute.isServerStreaming)
		for _, vr := range group.verbRoutes {
			if vr.isServerStreaming {
				groupIsStreaming = true
				break
			}
		}
		if groupIsStreaming {
			method = "POST"
		}
		if len(group.verbRoutes) == 0 && group.baseRoute != nil {
			// Simple case: single route, no custom verbs
			g.P("\t\tif !yield(\"", method, " ", group.serveMuxPath, "\", handle", serviceName, group.baseRoute.rpcMethod, "(connectHandler)) {")
			g.P("\t\t\treturn")
			g.P("\t\t}")
		} else {
			// Complex case: multiple routes with custom verbs need a dispatcher
			dispatcherName := dispatcherFuncName(serviceName, method, group.serveMuxPath)
			g.P("\t\tif !yield(\"", method, " ", group.serveMuxPath, "\", ", dispatcherName, "(connectHandler)) {")
			g.P("\t\t\treturn")
			g.P("\t\t}")
		}
	}

	g.P("\t}")
	g.P("}")
	g.P()
}

// dispatcherFuncName generates the dispatcher function name including method to avoid conflicts.
// e.g., ("Svc", "GET", "/v1/credentials/{name}") -> "dispatchSvcGetV1CredentialsName"
func dispatcherFuncName(serviceName, method, path string) string {
	return "dispatch" + serviceName + snakeToPascal(strings.ToLower(method)) + normalizePathToIdentifier(path)
}

// normalizePathToIdentifier converts a ServeMux path to a valid Go identifier suffix.
// e.g., "/v1/credentials/{name}" -> "V1CredentialsName"
func normalizePathToIdentifier(path string) string {
	var result strings.Builder
	capitalize := true

	for _, r := range path {
		if r == '/' || r == '{' || r == '}' || r == '.' || r == '-' {
			capitalize = true
			continue
		}
		if capitalize {
			result.WriteRune(toUpper(r))
			capitalize = false
		} else {
			result.WriteRune(r)
		}
	}

	return result.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 'a' + 'A'
	}
	return r
}

// generateStandaloneHandlers generates the standalone handler functions for each route.
func generateStandaloneHandlers(g *protogen.GeneratedFile, serviceName string, routes []routeInfo, pkgAlias, protoImportPath string) {
	for _, route := range routes {
		generateStandaloneHandler(g, serviceName, route, pkgAlias, protoImportPath)
	}
}

// generateStandaloneHandler generates a standalone handler function for a specific route.
func generateStandaloneHandler(g *protogen.GeneratedFile, serviceName string, route routeInfo, pkgAlias, protoImportPath string) {
	funcName := "handle" + serviceName + route.rpcMethod
	procedureConst := serviceName + route.rpcMethod + "Procedure"

	inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
	outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)

	if route.isServerStreaming {
		// Server-streaming: connectsse.Server handles the entire protocol translation.
		// It reads the nested JSON body sent by connectsse.Client and reconstructs the
		// Connect RPC request internally — no ForwardStream wrapper needed or wanted.
		// Gzip compression is disabled at the constructor level (see NewServiceAIPHandler)
		// so the Connect handler never compresses streaming responses.
		g.P("func ", funcName, "(connectHandler http.Handler) http.Handler {")
		g.P("\treturn &connectsse.Server{Handler: connectHandler}")
		g.P("}")
		g.P()
		return
	}

	g.P("func ", funcName, "(connectHandler http.Handler) http.Handler {")
	g.P("\treturn http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {")

	if route.method == "GET" || route.method == "DELETE" || route.bodyField == "" {
		g.P("\t\tconnectaip.ForwardWithBody[*", inputType, ", *", outputType, "](w, req, ", procedureConst, ", connectHandler, ", generateProtoLiteral(g, route.inputType, route.pathVars, pkgAlias, protoImportPath), ")")
	} else if route.bodyField == "*" && len(route.pathVars) == 0 {
		g.P("\t\tconnectaip.Forward[*", inputType, ", *", outputType, "](w, req, ", procedureConst, ", connectHandler)")
	} else if route.bodyField == "*" && len(route.pathVars) > 0 {
		g.P("\t\tconnectaip.ForwardWithPathVars[*", inputType, ", *", outputType, "](w, req, ", procedureConst, ", connectHandler, ", generateProtoLiteral(g, route.inputType, route.pathVars, pkgAlias, protoImportPath), ")")
	} else {
		g.P("\t\tconnectaip.Forward[*", inputType, ", *", outputType, "](w, req, ", procedureConst, ", connectHandler)")
	}

	g.P("\t})")
	g.P("}")
	g.P()
}

// generateDispatcherHandlers generates dispatcher handlers for route groups with custom verbs.
func generateDispatcherHandlers(g *protogen.GeneratedFile, serviceName string, groups []routeGroup, pkgAlias string) {
	for _, group := range groups {
		if len(group.verbRoutes) == 0 {
			continue // No dispatcher needed for simple routes
		}
		generateDispatcherHandler(g, serviceName, group, pkgAlias)
	}
}

// generateDispatcherHandler generates a dispatcher handler for a route group.
// The dispatcher uses req.PathValue to get the captured value, then checks
// which custom verb suffix it ends with to route to the correct RPC handler.
func generateDispatcherHandler(g *protogen.GeneratedFile, serviceName string, group routeGroup, _ string) {
	funcName := dispatcherFuncName(serviceName, group.method, group.serveMuxPath)

	// Find the path variable name that will contain the verb suffix.
	// Prefer the base route's variable name because the ServeMux pattern is
	// registered using the base route's path (see groupRoutesByPattern).
	var pathVarName string
	if group.baseRoute != nil && len(group.baseRoute.pathVars) > 0 {
		pathVarName = group.baseRoute.pathVars[len(group.baseRoute.pathVars)-1].name
	} else if len(group.verbRoutes) > 0 {
		pvs := group.verbRoutes[0].pathVars
		if len(pvs) > 0 {
			pathVarName = pvs[len(pvs)-1].name
		}
	}

	g.P("func ", funcName, "(connectHandler http.Handler) http.Handler {")
	g.P("\treturn http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {")

	if pathVarName != "" {
		g.P("\t\tpathVal := req.PathValue(\"", pathVarName, "\")")
		g.P("\t\tswitch {")

		// Generate cases for each custom verb route
		for _, route := range group.verbRoutes {
			g.P("\t\tcase strings.HasSuffix(pathVal, \"", route.customVerb, "\"):")
			g.P("\t\t\thandle", serviceName, route.rpcMethod, "(connectHandler).ServeHTTP(w, req)")
			g.P("\t\t\treturn")
		}

		// Generate default case for base route (no verb)
		if group.baseRoute != nil {
			g.P("\t\tdefault:")
			g.P("\t\t\thandle", serviceName, group.baseRoute.rpcMethod, "(connectHandler).ServeHTTP(w, req)")
		} else {
			g.P("\t\tdefault:")
			g.P("\t\t\thttp.NotFound(w, req)")
		}

		g.P("\t\t}")
	} else {
		// No path variable - this shouldn't happen but handle it
		if group.baseRoute != nil {
			g.P("\t\thandle", serviceName, group.baseRoute.rpcMethod, "(connectHandler).ServeHTTP(w, req)")
		} else {
			g.P("\t\thttp.NotFound(w, req)")
		}
	}

	g.P("\t})")
	g.P("}")
	g.P()
}

// generateProtoLiteral generates a proto struct literal for path variables.
// Example: for pathVars [{fieldPath: "name", prefix: "credentials/"}] and inputType GetCredentialRequest
// generates: &credentialsv1.GetCredentialRequest{Name: "credentials/" + req.PathValue("name")}
// For nested: [{fieldPath: "credential.name", prefix: "credentials/"}] and inputType UpdateCredentialRequest
// generates: &credentialsv1.UpdateCredentialRequest{Credential: &credentialsv1.Credential{Name: "credentials/" + req.PathValue("name")}}
func generateProtoLiteral(g *protogen.GeneratedFile, inputType *protogen.Message, pathVars []pathVar, pkgAlias, protoImportPath string) string {
	inputTypeName := qualifiedTypeName(g, inputType.GoIdent, pkgAlias, protoImportPath)
	if len(pathVars) == 0 {
		return "&" + inputTypeName + "{}"
	}

	var sb strings.Builder
	sb.WriteString("&")
	sb.WriteString(inputTypeName)
	sb.WriteString("{")

	first := true
	for _, pv := range pathVars {
		if pv.fieldPath == "" {
			continue // non-primary multi-wildcard var: no field assignment
		}
		if !first {
			sb.WriteString(", ")
		}
		first = false
		generateNestedFieldAssignment(g, &sb, inputType, strings.Split(pv.fieldPath, "."), pv, pkgAlias, protoImportPath)
	}

	sb.WriteString("}")
	return sb.String()
}

// generateNestedFieldAssignment generates the assignment for a potentially nested field path.
func generateNestedFieldAssignment(g *protogen.GeneratedFile, sb *strings.Builder, msg *protogen.Message, fieldParts []string, pv pathVar, pkgAlias, protoImportPath string) {
	if len(fieldParts) == 0 {
		return
	}

	fieldName := fieldParts[0]
	var targetField *protogen.Field
	for _, f := range msg.Fields {
		if string(f.Desc.Name()) == fieldName {
			targetField = f
			break
		}
	}

	if targetField == nil {
		return
	}

	sb.WriteString(targetField.GoName)
	sb.WriteString(": ")

	if len(fieldParts) == 1 {
		if pv.multiGroup != nil {
			// Multi-wildcard composite: reconstruct field from multiple path vars.
			// E.g., {name=agents/*/slos/*} → "agents/" + pathValue("name_0") + "/slos/" + pathValue("name_1")
			mg := pv.multiGroup
			if mg.prefix != "" {
				fmt.Fprintf(sb, "%q", mg.prefix)
				sb.WriteString(" + ")
			}
			for vi, varName := range mg.names {
				isLast := vi == len(mg.names)-1
				if isLast && mg.lastVerb != "" {
					fmt.Fprintf(sb, "strings.TrimSuffix(req.PathValue(%q), %q)", varName, mg.lastVerb)
				} else {
					fmt.Fprintf(sb, "req.PathValue(%q)", varName)
				}
				if vi < len(mg.seps) {
					fmt.Fprintf(sb, " + %q + ", mg.seps[vi])
				}
			}
		} else {
			// Generate path value expression, with TrimSuffix for custom verbs
			pathValueExpr := pathVarValueExpr(pv)
			if pv.prefix != "" {
				sb.WriteString("\"")
				sb.WriteString(pv.prefix)
				sb.WriteString("\" + ")
				sb.WriteString(pathValueExpr)
			} else {
				sb.WriteString(pathValueExpr)
			}
		}
	} else if targetField.Message != nil {
		nestedTypeName := qualifiedTypeName(g, targetField.Message.GoIdent, pkgAlias, protoImportPath)
		sb.WriteString("&")
		sb.WriteString(nestedTypeName)
		sb.WriteString("{")
		generateNestedFieldAssignment(g, sb, targetField.Message, fieldParts[1:], pv, pkgAlias, protoImportPath)
		sb.WriteString("}")
	}
}

// pathVarValueExpr generates the Go expression to get a path variable's value.
// For variables with custom verbs, it wraps the PathValue in strings.TrimSuffix.
func pathVarValueExpr(pv pathVar) string {
	if pv.customVerb != "" {
		return fmt.Sprintf("strings.TrimSuffix(req.PathValue(%q), %q)", pv.name, pv.customVerb)
	}
	return fmt.Sprintf("req.PathValue(%q)", pv.name)
}

// getHTTPRule extracts the google.api.http annotation from a method.
func getHTTPRule(method *protogen.Method) *annotations.HttpRule {
	opts := method.Desc.Options().(*descriptorpb.MethodOptions)
	if opts == nil {
		return nil
	}
	ext, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok {
		return nil
	}
	return ext
}

// parseHTTPRule parses an HttpRule into a routeInfo.
func parseHTTPRule(method *protogen.Method, rule *annotations.HttpRule) *routeInfo {
	var httpMethod, pattern string

	switch p := rule.GetPattern().(type) {
	case *annotations.HttpRule_Get:
		httpMethod = "GET"
		pattern = p.Get
	case *annotations.HttpRule_Post:
		httpMethod = "POST"
		pattern = p.Post
	case *annotations.HttpRule_Delete:
		httpMethod = "DELETE"
		pattern = p.Delete
	case *annotations.HttpRule_Patch:
		httpMethod = "PATCH"
		pattern = p.Patch
	case *annotations.HttpRule_Put:
		httpMethod = "PUT"
		pattern = p.Put
	default:
		return nil
	}

	if pattern == "" {
		return nil
	}

	pathVars, serveMuxPath, customVerb, ok := parseURLPatternToServeMux(pattern)
	if !ok {
		return nil
	}

	bodyField := rule.GetBody()
	if bodyField != "" && bodyField != "*" {
		panic(fmt.Sprintf("AIP handler generation only supports body: \"*\" or empty body, got: %q for method %s", bodyField, method.GoName))
	}

	return &routeInfo{
		method:            httpMethod,
		pattern:           pattern,
		bodyField:         bodyField,
		rpcMethod:         method.GoName,
		inputType:         method.Input,
		outputType:        method.Output,
		pathVars:          pathVars,
		serveMuxPath:      serveMuxPath,
		customVerb:        customVerb,
		isServerStreaming: method.Desc.IsStreamingServer(),
	}
}

// parseURLPatternToServeMux converts a google.api.http URL pattern to a Go 1.22+ ServeMux pattern.
// Returns (pathVars, serveMuxPath, customVerb, ok).
// Examples:
//
//	"/v1/customers" -> [], "/v1/customers", "", true
//	"/v1/{name=customers/*}" -> [{...}], "/v1/customers/{name}", "", true
//	"/v1/{customer.name=customers/*}" -> [{...}], "/v1/customers/{name}", "", true
//	"/v1/{name=customers/*/items/*}" -> [{...},{...}], "/v1/customers/{name_0}/items/{name_1}", "", true
//	"/v1/customers:purge" -> [], "/v1/customers:purge", "", true
//	"/v1/{name=customers/*}:action" -> [{...}], "/v1/customers/{name}", ":action", true
func parseURLPatternToServeMux(pattern string) ([]pathVar, string, string, bool) {
	var pathVars []pathVar
	var result strings.Builder
	var customVerb string
	i := 0

	for i < len(pattern) {
		if pattern[i] == '{' {
			end := strings.IndexByte(pattern[i:], '}')
			if end == -1 {
				result.WriteByte(pattern[i])
				i++
				continue
			}

			placeholder := pattern[i+1 : i+end]
			fieldPath := placeholder
			varPattern := ""
			hasWildcard := false
			isRestOfPath := false
			prefix := ""

			if name, pat, found := strings.Cut(placeholder, "="); found {
				fieldPath = name
				varPattern = pat
				starCount := strings.Count(pat, "*")
				hasWildcard = starCount > 0

				// Determine if this should use a rest-of-path wildcard
				// - Single trailing "*" (like "customers/*") -> use single segment {name}
				// - Multiple "*" or complex pattern -> use rest-of-path {name...}
				isRestOfPath = starCount > 1 || (starCount == 1 && !strings.HasSuffix(pat, "*"))

				// Compute the prefix up to (and including) the first wildcard position
				// For "customers/*" -> prefix is "customers/"
				// For "customers/*/items/*" -> prefix is "customers/" (stop at first *)
				if prefixPart, _, found := strings.Cut(varPattern, "*"); found {
					prefix = prefixPart
				} else {
					prefix = varPattern
				}
				result.WriteString(prefix)
			}

			// Check what comes after the closing brace
			afterBrace := pattern[i+end+1:]

			// Check for custom action pattern (":action" after the closing brace)
			// Extract the verb and exclude it from the ServeMux path
			if hasWildcard && strings.HasPrefix(afterBrace, ":") {
				// Extract the custom verb (e.g., ":revokeVersion")
				verbEnd := strings.IndexAny(afterBrace, "/")
				if verbEnd == -1 {
					customVerb = afterBrace
				} else {
					customVerb = afterBrace[:verbEnd]
				}
			}

			// Check if this is truly at the end of the path (for wildcard purposes)
			// ServeMux wildcards with "..." can only be at the very end
			isAtEnd := afterBrace == "" || afterBrace == "/" || (customVerb != "" && afterBrace == customVerb)

			// Use rest-of-path wildcard (...) only when:
			// 1. Pattern has multiple wildcards or wildcard not at end of pattern spec
			// 2. Wildcard is at the end of the URL path
			useWildcard := isRestOfPath && isAtEnd

			// Extract just the field name (last segment) for ServeMux
			// ServeMux doesn't allow dots in wildcard names, and full paths are verbose
			sanitizedName := fieldPath
			if lastDot := strings.LastIndex(fieldPath, "."); lastDot >= 0 {
				sanitizedName = fieldPath[lastDot+1:]
			}

			// Multi-wildcard expansion: when the pattern has more than one "*", expand
			// into explicit path segments to avoid conflicting with other services that
			// also use {name...} under the same base path.
			// E.g., {name=agents/*/slos/*} → agents/{name_0}/slos/{name_1}
			// rather than the ambiguous agents/{name...}.
			starCount := strings.Count(varPattern, "*")
			if starCount > 1 {
				parts := strings.Split(varPattern, "*") // e.g. ["agents/", "/slos/", ""]
				numWildcards := len(parts) - 1

				// Build the inter-wildcard separators (between wildcard i and i+1)
				seps := make([]string, numWildcards-1)
				for si := range seps {
					seps[si] = parts[si+1]
				}

				// Build sub-var names: name_0, name_1, …
				subNames := make([]string, numWildcards)
				for wi := range subNames {
					subNames[wi] = fmt.Sprintf("%s_%d", sanitizedName, wi)
				}

				// Write ServeMux path segments (prefix was already written above)
				for wi := range numWildcards {
					result.WriteString("{")
					result.WriteString(subNames[wi])
					result.WriteString("}")
					if wi < numWildcards-1 {
						result.WriteString(parts[wi+1])
					}
				}
				// Trailing literal after last wildcard (parts[numWildcards]);
				// usually empty for patterns ending with *, but handle the general case.
				if trailing := parts[numWildcards]; trailing != "" {
					// If it's just the customVerb, skip (already excluded from ServeMux path)
					if customVerb == "" || !strings.HasPrefix(trailing, customVerb) {
						result.WriteString(trailing)
					}
				}

				// Create shared multiVarGroup for all sub-vars
				mg := &multiVarGroup{
					fieldPath: fieldPath,
					prefix:    parts[0],
					seps:      seps,
					names:     subNames,
					lastVerb:  customVerb,
				}

				for wi, subName := range subNames {
					fp := ""
					if wi == 0 {
						fp = fieldPath // only the primary var generates a field assignment
					}
					mgCopy := *mg
					mgCopy.idx = wi
					pv := pathVar{
						name:       subName,
						fieldPath:  fp,
						wildcard:   true,
						multiGroup: &mgCopy,
					}
					pathVars = append(pathVars, pv)
				}

				i += end + 1
				if customVerb != "" && strings.HasPrefix(pattern[i:], customVerb) {
					i += len(customVerb)
				}
				continue
			}

			// Add the ServeMux wildcard placeholder
			result.WriteString("{")
			result.WriteString(sanitizedName)
			if useWildcard {
				result.WriteString("...")
			}
			result.WriteString("}")

			pv := pathVar{
				name:       sanitizedName,
				fieldPath:  fieldPath,
				prefix:     prefix,
				wildcard:   hasWildcard,
				customVerb: customVerb,
			}
			pathVars = append(pathVars, pv)

			i += end + 1

			// Skip past the custom verb in the input pattern (don't add to ServeMux path)
			if customVerb != "" && strings.HasPrefix(pattern[i:], customVerb) {
				i += len(customVerb)
			}
		} else {
			result.WriteByte(pattern[i])
			i++
		}
	}

	return pathVars, result.String(), customVerb, true
}

// ============================================================================
// Client Generation
// ============================================================================

// qualifiedTypeName returns the Go type expression for a message type referenced
// in the generated file. When the type is from the same proto package as the file
// being generated, it uses the pre-declared pkgAlias to avoid adding a duplicate
// import alongside the one in generateImports. For cross-package types (e.g.,
// emptypb.Empty for google.protobuf.Empty), it delegates to g.QualifiedGoIdent
// which registers the import automatically (protogen prepends a separate import
// block for these — valid Go, just two import blocks in the file).
//
// Known limitation: protogen's automatic import resolution does not see names
// claimed by the manual import block (`pkgAlias`, `connectaip`, `connect`,
// `connectsse`). If a generated file's local pkgAlias literally matches a
// cross-package alias protogen would assign — e.g., a proto with
// `option go_package = "..../emptypb;emptypb"` returning `google.protobuf.Empty`
// — the file ends up with two `emptypb` imports and won't compile. Avoiding
// this would require switching the file to use protogen-managed imports for
// everything (no manual `import (...)` block); deferred to a follow-up.
func qualifiedTypeName(g *protogen.GeneratedFile, ident protogen.GoIdent, pkgAlias, protoImportPath string) string {
	if string(ident.GoImportPath) == protoImportPath {
		return pkgAlias + "." + ident.GoName
	}
	return g.QualifiedGoIdent(ident)
}

// generateServiceClient generates the AIP client for a service.
func generateServiceClient(g *protogen.GeneratedFile, service *protogen.Service, pkgAlias, protoImportPath string) {
	var routes []routeInfo
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		httpRule := getHTTPRule(method)
		if httpRule == nil {
			continue
		}
		route := parseHTTPRule(method, httpRule)
		if route == nil {
			continue
		}
		// Skip routes with non-string path parameters (e.g., bytes fields)
		// These can't be easily converted to URL path segments
		if !hasOnlyStringPathParams(route, method.Input) {
			continue
		}
		routes = append(routes, *route)
	}

	if len(routes) == 0 {
		return
	}

	serviceName := service.GoName
	clientName := serviceName + "AIPClient"
	// When every RPC on the service has a usable HTTP rule, the AIP client
	// is a complete implementation of the standard {Service}Client interface
	// emitted by protoc-gen-connect-go and we return that directly so callers
	// can use it as a drop-in replacement. We also emit `type {Service}AIPClient =
	// {Service}Client` so existing downstream code that types variables as
	// {Service}AIPClient keeps compiling after regeneration.
	//
	// When some RPCs are filtered out (gRPC-only, client-streaming, unsupported
	// path params), we fall back to emitting an AIP-specific interface so the
	// generated file still compiles — partial coverage cannot satisfy the
	// standard interface.
	allMethodsCovered := len(routes) == len(service.Methods)
	clientInterface := serviceName + "Client"
	if allMethodsCovered {
		g.P("// ", clientName, " is an alias for the standard ", clientInterface, " interface.")
		g.P("// All RPCs on ", serviceName, " have HTTP rules, so the AIP client is a")
		g.P("// drop-in replacement for ", clientInterface, "; this alias is kept for")
		g.P("// backwards compatibility with code that types variables as ", clientName, ".")
		g.P("type ", clientName, " = ", clientInterface)
		g.P()
	} else {
		clientInterface = clientName
		g.P("// ", clientName, " is an AIP client for ", serviceName, ".")
		g.P("// ", serviceName, " has RPCs without HTTP rules; use the connect-go-generated")
		g.P("// ", serviceName, "Client (via New", serviceName, "Client) for full coverage.")
		g.P("type ", clientName, " interface {")
		for _, route := range routes {
			inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
			outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)
			if route.isServerStreaming {
				g.P("\t", route.rpcMethod, "(ctx context.Context, req *connect.Request[", inputType, "]) (*connect.ServerStreamForClient[", outputType, "], error)")
			} else {
				g.P("\t", route.rpcMethod, "(ctx context.Context, req *connect.Request[", inputType, "]) (*connect.Response[", outputType, "], error)")
			}
		}
		g.P("}")
		g.P()
	}

	implName := strings.ToLower(serviceName[:1]) + serviceName[1:] + "AIPClient"
	g.P("type ", implName, " struct {")
	for _, route := range routes {
		fieldName := strings.ToLower(route.rpcMethod[:1]) + route.rpcMethod[1:]
		inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
		outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)
		if route.isServerStreaming {
			g.P("\t", fieldName, " *connect.Client[", inputType, ", ", outputType, "]")
		} else {
			g.P("\t", fieldName, " *connectaip.Client[", inputType, ", ", outputType, "]")
		}
	}
	g.P("}")
	g.P()

	// Generate constructor
	g.P("// New", clientName, " creates a new AIP client for ", serviceName, ".")
	if allMethodsCovered {
		g.P("// The returned client satisfies the standard ", clientInterface, " interface,")
		g.P("// so it can be used as a drop-in replacement for New", clientInterface, ".")
	}
	g.P("func New", clientName, "(httpClient connect.HTTPClient, baseURL string, opts ...connectaip.ClientOption) ", clientInterface, " {")
	g.P("\treturn &", implName, "{")
	for _, route := range routes {
		fieldName := strings.ToLower(route.rpcMethod[:1]) + route.rpcMethod[1:]
		procedureConst := serviceName + route.rpcMethod + "Procedure"

		if route.isServerStreaming {
			inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
			outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)
			restPath := route.serveMuxPath + route.customVerb
			pathVarFnArg := "nil"
			if len(route.pathVars) > 0 {
				pathVarFnArg = serviceName + route.rpcMethod + "SSEPathVars"
			}
			g.P("\t\t", fieldName, ": connect.NewClient[", inputType, ", ", outputType, "](")
			g.P("\t\t\tconnectaip.NewSSEClient(httpClient, baseURL+\"", restPath, "\", ", pathVarFnArg, ", opts...),")
			g.P("\t\t\tconnectaip.SSEProcedureURL(baseURL, ", procedureConst, "),")
			g.P("\t\t\tappend([]connect.ClientOption{connect.WithProtoJSON()}, connectaip.ConnectClientOptions(opts...)...)...,")
			g.P("\t\t),")
		} else {
			inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
			outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)

			// Build MethodSpec
			g.P("\t\t", fieldName, ": connectaip.NewClient[", inputType, ", ", outputType, "](")
			g.P("\t\t\thttpClient, baseURL,")
			g.P("\t\t\tconnectaip.MethodSpec{")
			g.P("\t\t\t\tHTTPMethod: \"", route.method, "\",")
			g.P("\t\t\t\tURLPattern: \"", route.serveMuxPath+route.customVerb, "\",")
			g.P("\t\t\t\tProcedure:  ", procedureConst, ",")
			if len(route.pathVars) > 0 {
				g.P("\t\t\t\tPathVars: []connectaip.PathVar{")
				for _, pv := range route.pathVars {
					placeholder := "{" + pv.name
					if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
						placeholder += "..."
					}
					placeholder += "}"
					g.P("\t\t\t\t\t{Placeholder: \"", placeholder, "\", Prefix: \"", pv.prefix, "\"},")
				}
				g.P("\t\t\t\t},")
			}
			g.P("\t\t\t},")

			// Path var extractor function
			if len(route.pathVars) > 0 {
				g.P("\t\t\t", serviceName, route.rpcMethod, "PathVars,")
			} else {
				g.P("\t\t\tnil,")
			}

			// Query param extractor function (for GET/DELETE or empty body methods)
			if route.method == "GET" || route.method == "DELETE" || route.bodyField == "" {
				if hasQueryParams(route) {
					g.P("\t\t\t", serviceName, route.rpcMethod, "Query,")
				} else {
					g.P("\t\t\tfunc(*", inputType, ") map[string]string { return nil },")
				}
			} else {
				g.P("\t\t\tnil,")
			}

			g.P("\t\t\topts...,")
			g.P("\t\t),")
		}
	}
	g.P("\t}")
	g.P("}")
	g.P()

	// Generate path var extractor functions (unary only)
	for _, route := range routes {
		if !route.isServerStreaming && len(route.pathVars) > 0 {
			generatePathVarExtractor(g, serviceName, route, pkgAlias, protoImportPath)
		}
	}

	// Generate SSE path var extractor functions (streaming with path vars)
	for _, route := range routes {
		if route.isServerStreaming && len(route.pathVars) > 0 {
			generateSSEPathVarExtractor(g, serviceName, route)
		}
	}

	// Generate query param extractor functions (unary only)
	for _, route := range routes {
		if !route.isServerStreaming && (route.method == "GET" || route.method == "DELETE" || route.bodyField == "") && hasQueryParams(route) {
			generateQueryExtractor(g, serviceName, route, pkgAlias, protoImportPath)
		}
	}

	// Generate methods (one-line delegations)
	for _, route := range routes {
		generateClientMethod(g, implName, route, pkgAlias, protoImportPath)
	}
}

// generateClientMethod generates a single client method (one-line delegation).
// Method signatures match the standard {Service}Client interface from
// protoc-gen-connect-go so the AIP client is assignable to it.
func generateClientMethod(g *protogen.GeneratedFile, implName string, route routeInfo, pkgAlias, protoImportPath string) {
	fieldName := strings.ToLower(route.rpcMethod[:1]) + route.rpcMethod[1:]

	if route.isServerStreaming {
		inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
		outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)
		g.P("func (c *", implName, ") ", route.rpcMethod, "(ctx context.Context, req *connect.Request[", inputType, "]) (*connect.ServerStreamForClient[", outputType, "], error) {")
		g.P("\treturn c.", fieldName, ".CallServerStream(ctx, req)")
		g.P("}")
		g.P()
		return
	}

	inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
	outputType := qualifiedTypeName(g, route.outputType.GoIdent, pkgAlias, protoImportPath)

	g.P("func (c *", implName, ") ", route.rpcMethod, "(ctx context.Context, req *connect.Request[", inputType, "]) (*connect.Response[", outputType, "], error) {")
	g.P("\treturn c.", fieldName, ".CallRequest(ctx, req)")
	g.P("}")
	g.P()
}

// generatePathVarExtractor generates a function to extract path variables from a request.
func generatePathVarExtractor(g *protogen.GeneratedFile, serviceName string, route routeInfo, pkgAlias, protoImportPath string) {
	inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
	funcName := serviceName + route.rpcMethod + "PathVars"

	g.P("func ", funcName, "(req *", inputType, ") map[string]string {")
	g.P("\treturn map[string]string{")
	for _, pv := range route.pathVars {
		placeholder := "{" + pv.name
		if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
			placeholder += "..."
		}
		placeholder += "}"

		if pv.multiGroup != nil {
			// Multi-wildcard: extract each sub-var from the full field value by splitting.
			// E.g., for name = "agents/foo/slos/bar" with prefix "agents/" and sep "/slos/":
			//   name_0 → connectaip.SplitMultiWildcard(req.GetName(), "agents/", "/slos/", 0)
			//   name_1 → connectaip.SplitMultiWildcard(req.GetName(), "agents/", "/slos/", 1)
			// Using connectaip.SplitMultiWildcard avoids index-out-of-range panics on malformed names.
			mg := pv.multiGroup
			fieldAccessor := protoFieldAccessor(mg.fieldPath)

			if len(mg.names) == 2 {
				// Two-wildcard case: use connectaip.SplitMultiWildcard for safe (non-panicking) access.
				sep := mg.seps[0]
				g.P("\t\t\"", placeholder, "\": connectaip.SplitMultiWildcard(", fieldAccessor, ", ", fmt.Sprintf("%q", mg.prefix), ", ", fmt.Sprintf("%q", sep), ", ", mg.idx, "),")
			} else {
				// General N-wildcard case: chain SplitN calls. For now, use the full field
				// value for the first var and progressively strip prefixes for subsequent ones.
				// This covers the common 2-wildcard case; deeper nesting is uncommon.
				g.P("\t\t\"", placeholder, "\": ", fieldAccessor, ", // TODO: multi-segment split for index ", mg.idx)
			}
		} else {
			fieldAccessor := protoFieldAccessor(pv.fieldPath)
			g.P("\t\t\"", placeholder, "\": ", fieldAccessor, ",")
		}
	}
	g.P("\t}")
	g.P("}")
	g.P()
}

// generateSSEPathVarExtractor generates a function that extracts path variable values from
// a raw JSON message (as produced by connectsse.Client) for server-streaming routes.
// It handles both simple fields ("name") and nested fields ("session.name").
// The function signature is: func(msgJSON []byte) iter.Seq2[string, string].
func generateSSEPathVarExtractor(g *protogen.GeneratedFile, serviceName string, route routeInfo) {
	funcName := serviceName + route.rpcMethod + "SSEPathVars"
	g.P("func ", funcName, "(msgJSON []byte) iter.Seq2[string, string] {")
	g.P("\treturn func(yield func(string, string) bool) {")
	g.P("\t\tvar fields map[string]json.RawMessage")
	g.P("\t\t_ = json.Unmarshal(msgJSON, &fields)")
	for i, pv := range route.pathVars {
		jsonPath := jsonFieldPath(route.inputType, pv.fieldPath)
		placeholder := "{" + pv.name
		if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
			placeholder += "..."
		}
		placeholder += "}"

		// Generate nested JSON access for each level of the dotted field path.
		// Intermediate levels unmarshal into map[string]json.RawMessage; the final
		// level unmarshals into a string.
		indent := "\t\t"
		currentMap := "fields"
		for depth, jsonName := range jsonPath {
			rawVar := fmt.Sprintf("raw%d_%d", i, depth)
			if depth < len(jsonPath)-1 {
				nestedVar := fmt.Sprintf("nested%d_%d", i, depth)
				g.P(indent, "if ", rawVar, ", ok := ", currentMap, "[\"", jsonName, "\"]; ok {")
				indent += "\t"
				g.P(indent, "var ", nestedVar, " map[string]json.RawMessage")
				g.P(indent, "_ = json.Unmarshal(", rawVar, ", &", nestedVar, ")")
				currentMap = nestedVar
			} else {
				g.P(indent, "if ", rawVar, ", ok := ", currentMap, "[\"", jsonName, "\"]; ok {")
				indent += "\t"
				g.P(indent, "var val string")
				g.P(indent, "_ = json.Unmarshal(", rawVar, ", &val)")
				if pv.prefix != "" {
					g.P(indent, "val = strings.TrimPrefix(val, \"", pv.prefix, "\")")
				}
				g.P(indent, "if val != \"\" {")
				g.P(indent, "\tif !yield(\"", placeholder, "\", val) {")
				g.P(indent, "\t\treturn")
				g.P(indent, "\t}")
				g.P(indent, "}")
			}
		}
		for range jsonPath {
			indent = indent[:len(indent)-1]
			g.P(indent, "}")
		}
	}
	g.P("\t}")
	g.P("}")
	g.P()
}

// jsonFieldPath returns the sequence of protojson field names (camelCase) for a
// possibly dotted field path, traversing nested message types as needed.
// E.g. "session.name" on a message returns ["session", "name"] using JSON names.
func jsonFieldPath(msg *protogen.Message, fieldPath string) []string {
	parts := strings.Split(fieldPath, ".")
	result := make([]string, 0, len(parts))
	current := msg
	for _, part := range parts {
		if current == nil {
			result = append(result, part)
			continue
		}
		found := false
		for _, f := range current.Fields {
			if string(f.Desc.Name()) == part {
				result = append(result, f.Desc.JSONName())
				if f.Message != nil {
					current = f.Message
				} else {
					current = nil
				}
				found = true
				break
			}
		}
		if !found {
			result = append(result, part)
			current = nil
		}
	}
	return result
}

// generateQueryExtractor generates a function to extract query parameters from a request.
func generateQueryExtractor(g *protogen.GeneratedFile, serviceName string, route routeInfo, pkgAlias, protoImportPath string) {
	inputType := qualifiedTypeName(g, route.inputType.GoIdent, pkgAlias, protoImportPath)
	funcName := serviceName + route.rpcMethod + "Query"

	// Create a set of path variable field paths for quick lookup
	pathVarFields := make(map[string]bool)
	for _, pv := range route.pathVars {
		pathVarFields[pv.fieldPath] = true
	}

	g.P("func ", funcName, "(req *", inputType, ") map[string]string {")
	g.P("\tresult := make(map[string]string)")

	for _, field := range route.inputType.Fields {
		fieldPath := string(field.Desc.Name())
		if pathVarFields[fieldPath] {
			continue
		}

		fieldAccessor := "req.Get" + field.GoName + "()"
		jsonName := field.Desc.JSONName()

		switch field.Desc.Kind().String() {
		case "string":
			g.P("\tif v := ", fieldAccessor, "; v != \"\" {")
			g.P("\t\tresult[\"", jsonName, "\"] = v")
			g.P("\t}")
		case "int32", "int64", "uint32", "uint64":
			g.P("\tif v := ", fieldAccessor, "; v != 0 {")
			g.P("\t\tresult[\"", jsonName, "\"] = fmt.Sprint(v)")
			g.P("\t}")
		case "float", "double":
			g.P("\tif v := ", fieldAccessor, "; v != 0 {")
			g.P("\t\tresult[\"", jsonName, "\"] = fmt.Sprint(v)")
			g.P("\t}")
		case "bool":
			g.P("\tif v := ", fieldAccessor, "; v {")
			g.P("\t\tresult[\"", jsonName, "\"] = \"true\"")
			g.P("\t}")
		case "enum":
			g.P("\tif v := ", fieldAccessor, "; v != 0 {")
			g.P("\t\tresult[\"", jsonName, "\"] = fmt.Sprint(int32(v))")
			g.P("\t}")
		}
	}

	g.P("\treturn result")
	g.P("}")
	g.P()
}

// hasQueryParams checks if a route has any query parameters to extract.
func hasQueryParams(route routeInfo) bool {
	pathVarFields := make(map[string]bool)
	for _, pv := range route.pathVars {
		pathVarFields[pv.fieldPath] = true
	}

	for _, field := range route.inputType.Fields {
		fieldPath := string(field.Desc.Name())
		if pathVarFields[fieldPath] {
			continue
		}
		switch field.Desc.Kind().String() {
		case "string", "int32", "int64", "uint32", "uint64", "bool", "float", "double", "enum":
			return true
		}
	}
	return false
}

// hasOnlyStringPathParams checks if all path parameters in a route are string type.
// Returns false if any path parameter is a non-string type (e.g., bytes).
func hasOnlyStringPathParams(route *routeInfo, inputMsg *protogen.Message) bool {
	for _, pv := range route.pathVars {
		field := findFieldByPath(pv.fieldPath, inputMsg)
		if field == nil {
			continue
		}
		// Only allow string fields as path parameters
		if field.Desc.Kind().String() != "string" {
			return false
		}
	}
	return true
}

// findFieldByPath finds a field in a message by its dot-separated path.
// Example: "customer.name" finds the "name" field in the nested "customer" message.
func findFieldByPath(fieldPath string, msg *protogen.Message) *protogen.Field {
	parts := strings.Split(fieldPath, ".")
	currentMsg := msg

	for i, part := range parts {
		var found *protogen.Field
		for _, f := range currentMsg.Fields {
			if string(f.Desc.Name()) == part {
				found = f
				break
			}
		}
		if found == nil {
			return nil
		}
		if i == len(parts)-1 {
			return found
		}
		// Navigate into nested message
		if found.Message == nil {
			return nil
		}
		currentMsg = found.Message
	}
	return nil
}

// protoFieldAccessor returns the Go code to access a proto field given its path.
// Example: "customer.name" -> "req.GetCustomer().GetName()"
func protoFieldAccessor(fieldPath string) string {
	parts := strings.Split(fieldPath, ".")
	var sb strings.Builder
	sb.WriteString("req")
	for _, part := range parts {
		sb.WriteString(".Get")
		sb.WriteString(snakeToPascal(part))
		sb.WriteString("()")
	}
	return sb.String()
}

// snakeToPascal converts a snake_case string to PascalCase.
// Example: "customer_name" -> "CustomerName"
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
