# Code generated by protoc-gen-aip-py. DO NOT EDIT.

from collections.abc import Iterator, Mapping

import httpx

import test_pb2 as pb2
from google.protobuf import empty_pb2
from connectaip import Client, MethodSpec, PathVar, SSEClient


def _get_resource_path_vars(req: pb2.GetResourceRequest) -> dict[str, str]:
    return {
        "{name}": req.name,
    }

def _update_resource_path_vars(req: pb2.UpdateResourceRequest) -> dict[str, str]:
    return {
        "{name}": req.resource.name,
    }

def _list_resources_query(req: pb2.ListResourcesRequest) -> dict[str, str]:
    params: dict[str, str] = {}
    if req.page_size != 0:
        params["pageSize"] = str(req.page_size)
    if req.page_token:
        params["pageToken"] = req.page_token
    if req.filter:
        params["filter"] = req.filter
    if req.order_by:
        params["orderBy"] = req.order_by
    return params

def _list_versions_path_vars(req: pb2.ListVersionsRequest) -> dict[str, str]:
    return {
        "{name}": req.name,
    }

def _list_versions_query(req: pb2.ListVersionsRequest) -> dict[str, str]:
    params: dict[str, str] = {}
    if req.page_token:
        params["pageToken"] = req.page_token
    return params

def _delete_resource_path_vars(req: pb2.DeleteResourceRequest) -> dict[str, str]:
    return {
        "{name}": req.name,
    }

class TestServiceAIPClient:
    """AIP client for TestService."""

    def __init__(
        self,
        base_url: str,
        session: httpx.Client,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self._create_resource = Client[pb2.CreateResourceRequest, pb2.CreateResourceResponse](
            session=session,
            base_url=base_url,
            spec=MethodSpec("POST", "/v1/resources", []),
            response_type=pb2.CreateResourceResponse,
            path_var_fn=None,
            query_fn=None,
            headers=headers,
        )
        self._get_resource = Client[pb2.GetResourceRequest, pb2.GetResourceResponse](
            session=session,
            base_url=base_url,
            spec=MethodSpec("GET", "/v1/resources/{name}", [PathVar("{name}", "resources/")]),
            response_type=pb2.GetResourceResponse,
            path_var_fn=_get_resource_path_vars,
            query_fn=None,
            headers=headers,
        )
        self._update_resource = Client[pb2.UpdateResourceRequest, pb2.UpdateResourceResponse](
            session=session,
            base_url=base_url,
            spec=MethodSpec("PATCH", "/v1/resources/{name}", [PathVar("{name}", "resources/")]),
            response_type=pb2.UpdateResourceResponse,
            path_var_fn=_update_resource_path_vars,
            query_fn=None,
            headers=headers,
        )
        self._list_resources = Client[pb2.ListResourcesRequest, pb2.ListResourcesResponse](
            session=session,
            base_url=base_url,
            spec=MethodSpec("GET", "/v1/resources", []),
            response_type=pb2.ListResourcesResponse,
            path_var_fn=None,
            query_fn=_list_resources_query,
            headers=headers,
        )
        self._list_versions = Client[pb2.ListVersionsRequest, pb2.ListVersionsResponse](
            session=session,
            base_url=base_url,
            spec=MethodSpec("GET", "/v1/resources/{name}/versions", [PathVar("{name}", "resources/")]),
            response_type=pb2.ListVersionsResponse,
            path_var_fn=_list_versions_path_vars,
            query_fn=_list_versions_query,
            headers=headers,
        )
        self._stream_resources = SSEClient[pb2.CreateResourceRequest, pb2.CreateResourceResponse](
            session=session,
            base_url=base_url,
            procedure="/connectaip.test.v1.TestService/StreamResources",
            url_pattern="/v1/resources:stream",
            response_type=pb2.CreateResourceResponse,
            path_var_fn=None,
            path_vars=None,
            headers=headers,
        )
        self._delete_resource = Client[pb2.DeleteResourceRequest, empty_pb2.Empty](
            session=session,
            base_url=base_url,
            spec=MethodSpec("DELETE", "/v1/resources/{name}", [PathVar("{name}", "resources/")]),
            response_type=empty_pb2.Empty,
            path_var_fn=_delete_resource_path_vars,
            query_fn=None,
            headers=headers,
        )

    def create_resource(
        self,
        request: pb2.CreateResourceRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> pb2.CreateResourceResponse:
        return self._create_resource.call(request, headers=headers, timeout=timeout)

    def get_resource(
        self,
        request: pb2.GetResourceRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> pb2.GetResourceResponse:
        return self._get_resource.call(request, headers=headers, timeout=timeout)

    def update_resource(
        self,
        request: pb2.UpdateResourceRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> pb2.UpdateResourceResponse:
        return self._update_resource.call(request, headers=headers, timeout=timeout)

    def list_resources(
        self,
        request: pb2.ListResourcesRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> pb2.ListResourcesResponse:
        return self._list_resources.call(request, headers=headers, timeout=timeout)

    def list_versions(
        self,
        request: pb2.ListVersionsRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> pb2.ListVersionsResponse:
        return self._list_versions.call(request, headers=headers, timeout=timeout)

    def stream_resources(
        self,
        request: pb2.CreateResourceRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> Iterator[pb2.CreateResourceResponse]:
        return self._stream_resources.stream(request, headers=headers, timeout=timeout)

    def delete_resource(
        self,
        request: pb2.DeleteResourceRequest,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> empty_pb2.Empty:
        return self._delete_resource.call(request, headers=headers, timeout=timeout)

