package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	// Collect routes for all services first to determine if the file is needed
	// and whether any route has path variables (for the PathVar import).
	type serviceRoutes struct {
		service *protogen.Service
		routes  []routeInfo
	}
	var allServices []serviceRoutes
	hasPathVars := false
	hasStreaming := false

	for _, service := range file.Services {
		var routes []routeInfo
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil {
				continue
			}
			if !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			if method.Desc.IsStreamingServer() {
				route.streaming = true
				route.procedure = "/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name())
				hasStreaming = true
			}
			routes = append(routes, *route)
		}
		if len(routes) > 0 {
			allServices = append(allServices, serviceRoutes{service, routes})
			for _, r := range routes {
				if len(r.pathVars) > 0 {
					hasPathVars = true
				}
			}
		}
	}

	if len(allServices) == 0 {
		return
	}

	protoPath := string(file.Desc.Path())
	pythonPath := strings.TrimSuffix(protoPath, ".proto")
	pythonPath = strings.ReplaceAll(pythonPath, "/", ".")
	var protoDir, baseName string
	if slash := strings.LastIndex(protoPath, "/"); slash >= 0 {
		protoDir = protoPath[:slash+1]
		baseName = strings.TrimSuffix(protoPath[slash+1:], ".proto")
	} else {
		baseName = strings.TrimSuffix(protoPath, ".proto")
	}
	outputPath := protoDir + baseName + "_aip.py"

	resolver := newPyTypeResolver(file)
	for _, sr := range allServices {
		for _, route := range sr.routes {
			resolver.register(route.inputType)
			resolver.register(route.outputType)
		}
	}

	g := gen.NewGeneratedFile(outputPath, "")

	g.P("# Code generated by protoc-gen-aip-py. DO NOT EDIT.")
	g.P()
	if hasStreaming {
		g.P("from collections.abc import Iterator, Mapping")
	} else {
		g.P("from collections.abc import Mapping")
	}
	g.P()
	g.P("import httpx")
	g.P()
	g.P("import ", pythonPath+"_pb2 as pb2")
	for _, line := range resolver.importLines() {
		g.P(line)
	}
	var imports []string
	imports = append(imports, "Client", "MethodSpec")
	if hasPathVars {
		imports = append(imports, "PathVar")
	}
	if hasStreaming {
		imports = append(imports, "SSEClient")
	}
	g.P("from connectaip import ", strings.Join(imports, ", "))
	g.P()

	for _, sr := range allServices {
		generateServiceBody(g, sr.service, sr.routes, resolver)
	}
}

type routeInfo struct {
	rpcMethod    string
	method       string
	pattern      string
	serveMuxPath string
	pathVars     []pathVar
	bodyField    string
	inputType    *protogen.Message
	outputType   *protogen.Message
	streaming    bool
	procedure    string
}

type pathVar struct {
	name      string
	fieldPath string
	prefix    string
	wildcard  bool
}

// pyTypeResolver tracks message types referenced by the file under generation
// and produces the Python type expression for each, emitting any extra `import`
// lines needed to bring cross-package types into scope.
//
// Local types come from the always-present `import <pythonPath>_pb2 as pb2`.
// Well-known types (proto file path under `google/protobuf/`) come in via
// `from google.protobuf import <basename>_pb2` and are referenced as
// `<basename>_pb2.X`. Any other cross-file type is imported as
// `import <module>_pb2 as <basename>_pb2` (path mirrors the local
// proto-path-to-Python-module convention).
type pyTypeResolver struct {
	currentFile string

	// wktBaseNames is the set of basenames (e.g., "empty") needed from
	// google.protobuf — each contributes a `from google.protobuf import
	// <name>_pb2` line.
	wktBaseNames map[string]struct{}

	// otherFiles maps a non-local, non-WKT proto file path to its chosen
	// Python module alias (e.g. "other_pb2").
	otherFiles map[string]string
}

func newPyTypeResolver(file *protogen.File) *pyTypeResolver {
	return &pyTypeResolver{
		currentFile:  string(file.Desc.Path()),
		wktBaseNames: map[string]struct{}{},
		otherFiles:   map[string]string{},
	}
}

func (r *pyTypeResolver) register(msg *protogen.Message) {
	r.registerSource(string(msg.Desc.ParentFile().Path()), string(msg.Desc.Name()))
}

func (r *pyTypeResolver) registerSource(source, name string) {
	if source == r.currentFile {
		return
	}
	base := strings.TrimSuffix(source[strings.LastIndex(source, "/")+1:], ".proto")
	if isWellKnownProtoFile(source) {
		r.wktBaseNames[base] = struct{}{}
		return
	}
	if _, ok := r.otherFiles[source]; ok {
		return
	}
	r.otherFiles[source] = base + "_pb2"
}

func (r *pyTypeResolver) resolve(msg *protogen.Message) string {
	return r.resolveSource(string(msg.Desc.ParentFile().Path()), string(msg.Desc.Name()))
}

func (r *pyTypeResolver) resolveSource(source, name string) string {
	if source == r.currentFile {
		return "pb2." + name
	}
	base := strings.TrimSuffix(source[strings.LastIndex(source, "/")+1:], ".proto")
	if isWellKnownProtoFile(source) {
		return base + "_pb2." + name
	}
	return r.otherFiles[source] + "." + name
}

// importLines returns extra `import` statements (excluding the always-present
// local `import <pythonPath>_pb2 as pb2`), sorted by source for stable output.
func (r *pyTypeResolver) importLines() []string {
	var lines []string
	wktBases := make([]string, 0, len(r.wktBaseNames))
	for b := range r.wktBaseNames {
		wktBases = append(wktBases, b)
	}
	sort.Strings(wktBases)
	for _, b := range wktBases {
		lines = append(lines, fmt.Sprintf("from google.protobuf import %s_pb2", b))
	}
	sources := make([]string, 0, len(r.otherFiles))
	for s := range r.otherFiles {
		sources = append(sources, s)
	}
	sort.Strings(sources)
	for _, source := range sources {
		alias := r.otherFiles[source]
		modulePath := strings.ReplaceAll(strings.TrimSuffix(source, ".proto"), "/", ".")
		lines = append(lines, fmt.Sprintf("import %s_pb2 as %s", modulePath, alias))
	}
	return lines
}

func isWellKnownProtoFile(path string) bool {
	return strings.HasPrefix(path, "google/protobuf/")
}

func getHTTPRule(method *protogen.Method) *annotations.HttpRule {
	options := method.Desc.Options().(*descriptorpb.MethodOptions)
	if options == nil {
		return nil
	}
	ext := proto.GetExtension(options, annotations.E_Http)
	if ext == nil {
		return nil
	}
	return ext.(*annotations.HttpRule)
}

func parseHTTPRule(method *protogen.Method, rule *annotations.HttpRule) *routeInfo {
	var httpMethod, pattern string
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		httpMethod = "GET"
		pattern = p.Get
	case *annotations.HttpRule_Post:
		httpMethod = "POST"
		pattern = p.Post
	case *annotations.HttpRule_Put:
		httpMethod = "PUT"
		pattern = p.Put
	case *annotations.HttpRule_Delete:
		httpMethod = "DELETE"
		pattern = p.Delete
	case *annotations.HttpRule_Patch:
		httpMethod = "PATCH"
		pattern = p.Patch
	default:
		return nil
	}

	pathVars, serveMuxPath, ok := parsePathPattern(pattern)
	if !ok {
		return nil
	}

	return &routeInfo{
		rpcMethod:    string(method.Desc.Name()),
		method:       httpMethod,
		pattern:      pattern,
		serveMuxPath: serveMuxPath,
		pathVars:     pathVars,
		bodyField:    rule.Body,
		inputType:    method.Input,
		outputType:   method.Output,
	}
}

func parsePathPattern(pattern string) ([]pathVar, string, bool) {
	var pathVars []pathVar
	var result strings.Builder
	i := 0

	for i < len(pattern) {
		if pattern[i] == '{' {
			end := strings.IndexByte(pattern[i:], '}')
			if end == -1 {
				result.WriteByte(pattern[i])
				i++
				continue
			}

			placeholder := pattern[i+1 : i+end]
			fieldPath := placeholder
			varPattern := ""
			hasWildcard := false
			isRestOfPath := false
			prefix := ""

			if name, pat, found := strings.Cut(placeholder, "="); found {
				fieldPath = name
				varPattern = pat
				starCount := strings.Count(pat, "*")
				hasWildcard = starCount > 0
				isRestOfPath = starCount > 1 || (starCount == 1 && !strings.HasSuffix(pat, "*"))

				if idx := strings.Index(varPattern, "*"); idx >= 0 {
					prefix = varPattern[:idx]
				} else {
					prefix = varPattern
				}
				result.WriteString(prefix)
			}

			useWildcard := isRestOfPath

			sanitizedName := fieldPath
			if lastDot := strings.LastIndex(fieldPath, "."); lastDot >= 0 {
				sanitizedName = fieldPath[lastDot+1:]
			}

			result.WriteString("{")
			result.WriteString(sanitizedName)
			if useWildcard {
				result.WriteString("...")
			}
			result.WriteString("}")

			pathVars = append(pathVars, pathVar{
				name:      sanitizedName,
				fieldPath: fieldPath,
				prefix:    prefix,
				wildcard:  hasWildcard,
			})

			i += end + 1
		} else {
			result.WriteByte(pattern[i])
			i++
		}
	}

	return pathVars, result.String(), true
}

func hasOnlyStringPathParams(route *routeInfo, inputMsg *protogen.Message) bool {
	for _, pv := range route.pathVars {
		field := findFieldByPath(pv.fieldPath, inputMsg)
		if field == nil {
			continue
		}
		if field.Desc.Kind().String() != "string" {
			return false
		}
	}
	return true
}

func findFieldByPath(fieldPath string, msg *protogen.Message) *protogen.Field {
	parts := strings.Split(fieldPath, ".")
	currentMsg := msg

	for i, part := range parts {
		var found *protogen.Field
		for _, f := range currentMsg.Fields {
			if string(f.Desc.Name()) == part {
				found = f
				break
			}
		}
		if found == nil {
			return nil
		}
		if i == len(parts)-1 {
			return found
		}
		if found.Message == nil {
			return nil
		}
		currentMsg = found.Message
	}
	return nil
}

func generateServiceBody(g *protogen.GeneratedFile, service *protogen.Service, routes []routeInfo, resolver *pyTypeResolver) {
	for _, route := range routes {
		generatePathVarFn(g, route, resolver)
		generateQueryFn(g, route, resolver)
	}

	serviceName := service.GoName
	className := serviceName + "AIPClient"

	g.P()
	g.P("class ", className, ":")
	g.P("    \"\"\"AIP client for ", serviceName, ".\"\"\"")
	g.P()
	g.P("    def __init__(")
	g.P("        self,")
	g.P("        base_url: str,")
	g.P("        session: httpx.Client,")
	g.P("        headers: Mapping[str, str] | None = None,")
	g.P("    ) -> None:")

	for _, route := range routes {
		generateClientInit(g, route, resolver)
	}
	g.P()

	for _, route := range routes {
		generatePythonMethod(g, route, resolver)
	}
}

func generatePathVarFn(g *protogen.GeneratedFile, route routeInfo, resolver *pyTypeResolver) {
	if len(route.pathVars) == 0 {
		return
	}
	methodName := camelToSnake(route.rpcMethod)
	inputType := resolver.resolve(route.inputType)

	g.P()
	g.P("def _", methodName, "_path_vars(req: ", inputType, ") -> dict[str, str]:")
	g.P("    return {")
	for _, pv := range route.pathVars {
		fieldAccessor := pythonFieldAccessor(pv.fieldPath)
		placeholder := "{" + pv.name
		if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
			placeholder += "..."
		}
		placeholder += "}"
		g.P("        \"", placeholder, "\": ", fieldAccessor, ",")
	}
	g.P("    }")
}

func generateQueryFn(g *protogen.GeneratedFile, route routeInfo, resolver *pyTypeResolver) {
	if route.method != "GET" && route.method != "DELETE" {
		return
	}

	pathVarFields := make(map[string]bool)
	for _, pv := range route.pathVars {
		pathVarFields[pv.fieldPath] = true
	}

	var queryFields []*protogen.Field
	for _, field := range route.inputType.Fields {
		fieldPath := string(field.Desc.Name())
		if pathVarFields[fieldPath] {
			continue
		}
		kind := field.Desc.Kind().String()
		if kind == "string" || kind == "int32" || kind == "int64" || kind == "uint32" || kind == "uint64" || kind == "bool" {
			queryFields = append(queryFields, field)
		}
	}

	if len(queryFields) == 0 {
		return
	}

	methodName := camelToSnake(route.rpcMethod)
	inputType := resolver.resolve(route.inputType)

	g.P()
	g.P("def _", methodName, "_query(req: ", inputType, ") -> dict[str, str]:")
	g.P("    params: dict[str, str] = {}")
	for _, field := range queryFields {
		fieldPath := string(field.Desc.Name())
		fieldAccessor := "req." + fieldPath
		jsonName := field.Desc.JSONName()

		switch field.Desc.Kind().String() {
		case "string":
			g.P("    if ", fieldAccessor, ":")
			g.P("        params[\"", jsonName, "\"] = ", fieldAccessor)
		case "int32", "int64", "uint32", "uint64":
			g.P("    if ", fieldAccessor, " != 0:")
			g.P("        params[\"", jsonName, "\"] = str(", fieldAccessor, ")")
		case "bool":
			g.P("    if ", fieldAccessor, ":")
			g.P("        params[\"", jsonName, "\"] = \"true\"")
		}
	}
	g.P("    return params")
}

func generateClientInit(g *protogen.GeneratedFile, route routeInfo, resolver *pyTypeResolver) {
	methodName := camelToSnake(route.rpcMethod)
	inputType := resolver.resolve(route.inputType)
	outputType := resolver.resolve(route.outputType)

	pathVarFnStr := "None"
	if len(route.pathVars) > 0 {
		pathVarFnStr = "_" + methodName + "_path_vars"
	}

	if route.streaming {
		var pathVarsStr string
		if len(route.pathVars) > 0 {
			var parts []string
			for _, pv := range route.pathVars {
				placeholder := "{" + pv.name
				if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
					placeholder += "..."
				}
				placeholder += "}"
				if pv.prefix != "" {
					parts = append(parts, "PathVar(\""+placeholder+"\", \""+pv.prefix+"\")")
				} else {
					parts = append(parts, "PathVar(\""+placeholder+"\")")
				}
			}
			pathVarsStr = "[" + strings.Join(parts, ", ") + "]"
		} else {
			pathVarsStr = "None"
		}

		g.P("        self._", methodName, " = SSEClient[", inputType, ", ", outputType, "](")
		g.P("            session=session,")
		g.P("            base_url=base_url,")
		g.P("            procedure=\"", route.procedure, "\",")
		g.P("            url_pattern=\"", route.serveMuxPath, "\",")
		g.P("            response_type=", outputType, ",")
		g.P("            path_var_fn=", pathVarFnStr, ",")
		g.P("            path_vars=", pathVarsStr, ",")
		g.P("            headers=headers,")
		g.P("        )")
		return
	}

	var pathVarsStr string
	if len(route.pathVars) > 0 {
		var parts []string
		for _, pv := range route.pathVars {
			placeholder := "{" + pv.name
			if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
				placeholder += "..."
			}
			placeholder += "}"
			if pv.prefix != "" {
				parts = append(parts, "PathVar(\""+placeholder+"\", \""+pv.prefix+"\")")
			} else {
				parts = append(parts, "PathVar(\""+placeholder+"\")")
			}
		}
		pathVarsStr = "[" + strings.Join(parts, ", ") + "]"
	} else {
		pathVarsStr = "[]"
	}

	queryFnStr := "None"
	if route.method == "GET" || route.method == "DELETE" {
		pathVarFields := make(map[string]bool)
		for _, pv := range route.pathVars {
			pathVarFields[pv.fieldPath] = true
		}
		for _, field := range route.inputType.Fields {
			fieldPath := string(field.Desc.Name())
			if pathVarFields[fieldPath] {
				continue
			}
			kind := field.Desc.Kind().String()
			if kind == "string" || kind == "int32" || kind == "int64" || kind == "uint32" || kind == "uint64" || kind == "bool" {
				queryFnStr = "_" + methodName + "_query"
				break
			}
		}
	}

	g.P("        self._", methodName, " = Client[", inputType, ", ", outputType, "](")
	g.P("            session=session,")
	g.P("            base_url=base_url,")
	g.P("            spec=MethodSpec(\"", route.method, "\", \"", route.serveMuxPath, "\", ", pathVarsStr, "),")
	g.P("            response_type=", outputType, ",")
	g.P("            path_var_fn=", pathVarFnStr, ",")
	g.P("            query_fn=", queryFnStr, ",")
	g.P("            headers=headers,")
	g.P("        )")
}

func generatePythonMethod(g *protogen.GeneratedFile, route routeInfo, resolver *pyTypeResolver) {
	methodName := camelToSnake(route.rpcMethod)
	inputType := resolver.resolve(route.inputType)
	outputType := resolver.resolve(route.outputType)

	if route.streaming {
		g.P("    def ", methodName, "(")
		g.P("        self,")
		g.P("        request: ", inputType, ",")
		g.P("        *,")
		g.P("        headers: Mapping[str, str] | None = None,")
		g.P("        timeout: float | None = None,")
		g.P("    ) -> Iterator[", outputType, "]:")
		g.P("        return self._", methodName, ".stream(request, headers=headers, timeout=timeout)")
		g.P()
		return
	}

	g.P("    def ", methodName, "(")
	g.P("        self,")
	g.P("        request: ", inputType, ",")
	g.P("        *,")
	g.P("        headers: Mapping[str, str] | None = None,")
	g.P("        timeout: float | None = None,")
	g.P("    ) -> ", outputType, ":")
	g.P("        return self._", methodName, ".call(request, headers=headers, timeout=timeout)")
	g.P()
}

func pythonFieldAccessor(fieldPath string) string {
	parts := strings.Split(fieldPath, ".")
	var sb strings.Builder
	sb.WriteString("req")
	for _, part := range parts {
		sb.WriteString(".")
		sb.WriteString(part)
	}
	return sb.String()
}

func camelToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteByte(byte(r - 'A' + 'a'))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
