package main

import (
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	// Collect routes for all services first.  We need all services before creating
	// the output file so we can write a single file for proto files with multiple services.
	type serviceRoutes struct {
		service *protogen.Service
		routes  []routeInfo
	}
	var allServices []serviceRoutes
	hasStreaming := false

	for _, service := range file.Services {
		var routes []routeInfo
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() {
				continue
			}
			httpRule := getHTTPRule(method)
			if httpRule == nil {
				continue
			}
			route := parseHTTPRule(method, httpRule)
			if route == nil {
				continue
			}
			if !hasOnlyStringPathParams(route, method.Input) {
				continue
			}
			if method.Output.Desc.ParentFile().Path() != file.Desc.Path() {
				continue
			}
			if method.Desc.IsStreamingServer() {
				route.streaming = true
				route.procedure = "/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name())
				hasStreaming = true
			}
			routes = append(routes, *route)
		}
		if len(routes) > 0 {
			allServices = append(allServices, serviceRoutes{service, routes})
		}
	}

	if len(allServices) == 0 {
		return
	}

	protoPath := string(file.Desc.Path())
	protoDir := protoPath[:strings.LastIndex(protoPath, "/")]
	baseName := strings.TrimSuffix(protoPath[strings.LastIndex(protoPath, "/")+1:], ".proto")
	outputPath := protoDir + "/" + baseName + "_aip.ts"
	importPath := "./" + baseName + "_pb"

	g := gen.NewGeneratedFile(outputPath, "")

	g.P("// Code generated by protoc-gen-aip-ts. DO NOT EDIT.")
	g.P()
	g.P("import { create, fromJson, toJson, type DescMessage, type JsonValue, type MessageInitShape, type MessageShape, type Registry } from \"@bufbuild/protobuf\";")
	g.P("import * as pb from \"", importPath, "\";")
	g.P()
	g.P("export interface AIPClientOptions {")
	g.P("  headers?: Record<string, string>;")
	g.P("  fetch?: typeof fetch;")
	g.P("  registry: Registry;")
	g.P("}")
	g.P()
	g.P("const codeFromString: Record<string, number> = {")
	g.P("  canceled: 1, unknown: 2, invalid_argument: 3, deadline_exceeded: 4,")
	g.P("  not_found: 5, already_exists: 6, permission_denied: 7, resource_exhausted: 8,")
	g.P("  failed_precondition: 9, aborted: 10, out_of_range: 11, unimplemented: 12,")
	g.P("  internal: 13, unavailable: 14, data_loss: 15, unauthenticated: 16,")
	g.P("};")
	g.P()
	g.P("const httpStatusToCode: Record<number, number> = {")
	g.P("  400: 3, 401: 16, 403: 7, 404: 5, 409: 6, 412: 9, 429: 8, 501: 12, 503: 14, 504: 4,")
	g.P("};")
	g.P()
	g.P("export class AIPError extends Error {")
	g.P("  readonly code: number;")
	g.P("  constructor(code: number, message: string) {")
	g.P("    super(message);")
	g.P("    this.name = \"AIPError\";")
	g.P("    this.code = code;")
	g.P("  }")
	g.P("}")
	g.P()
	g.P("async function parseErrorResponse(response: Response): Promise<AIPError> {")
	g.P("  const body = await response.text();")
	g.P("  try {")
	g.P("    const json = JSON.parse(body);")
	g.P("    const code = codeFromString[json.code];")
	g.P("    if (code !== undefined) {")
	g.P("      return new AIPError(code, json.message ?? body);")
	g.P("    }")
	g.P("  } catch { /* fall through */ }")
	g.P("  return new AIPError(httpStatusToCode[response.status] ?? 13, body);")
	g.P("}")
	g.P()
	g.P("// biome-ignore lint/suspicious/noExplicitAny: recursive JSON walker")
	g.P("export function sanitizeAny(data: any, registry: Registry): any {")
	g.P("  if (Array.isArray(data)) {")
	g.P("    return data.map((item) => sanitizeAny(item, registry));")
	g.P("  }")
	g.P("  if (data !== null && typeof data === \"object\") {")
	g.P("    // Only protobuf Any JSON has @type = \"type.googleapis.com/...\" per")
	g.P("    // proto3 JSON spec. Guards against google.protobuf.Struct values that")
	g.P("    // happen to contain a string @type field (arbitrary JSON-like data).")
	g.P("    const typeUrl = data[\"@type\"];")
	g.P("    if (typeof typeUrl === \"string\" && typeUrl.startsWith(\"type.googleapis.com/\")) {")
	g.P("      const slash = typeUrl.lastIndexOf(\"/\");")
	g.P("      const typeName = slash >= 0 ? typeUrl.substring(slash + 1) : typeUrl;")
	g.P("      if (!registry.getMessage(typeName)) {")
	g.P("        // biome-ignore lint/suspicious/noConsole: observability for missing schema")
	g.P("        console.warn(")
	g.P("          `[aip] unknown Any type \"${typeUrl}\" not in registry; collapsed to empty object. Add the schema to anyRegistry to preserve this field.`,")
	g.P("        );")
	g.P("        return {};")
	g.P("      }")
	g.P("    }")
	g.P("    const result: Record<string, unknown> = {};")
	g.P("    for (const key of Object.keys(data)) {")
	g.P("      result[key] = sanitizeAny(data[key], registry);")
	g.P("    }")
	g.P("    return result;")
	g.P("  }")
	g.P("  return data;")
	g.P("}")
	g.P()
	g.P("export function fromJsonAny<T extends DescMessage>(")
	g.P("  schema: T, data: unknown, registry: Registry,")
	g.P("): MessageShape<T> {")
	g.P("  try {")
	g.P("    return fromJson(schema, data as JsonValue, { registry });")
	g.P("  } catch (e) {")
	g.P("    if (e instanceof Error && e.message.includes(\"not in the type registry\")) {")
	g.P("      return fromJson(schema, sanitizeAny(data, registry) as JsonValue, { registry });")
	g.P("    }")
	g.P("    throw e;")
	g.P("  }")
	g.P("}")
	g.P()

	if hasStreaming {
		generateSSEHelper(g)
	}

	for _, sr := range allServices {
		generateServiceBody(g, sr.service, sr.routes)
	}
}

type routeInfo struct {
	rpcMethod    string
	method       string
	pattern      string
	serveMuxPath string
	pathVars     []pathVar
	bodyField    string
	inputType    *protogen.Message
	outputType   *protogen.Message
	streaming    bool
	procedure    string
}

type pathVar struct {
	name      string
	fieldPath string
	prefix    string
	wildcard  bool
}

func getHTTPRule(method *protogen.Method) *annotations.HttpRule {
	options := method.Desc.Options().(*descriptorpb.MethodOptions)
	if options == nil {
		return nil
	}
	ext := proto.GetExtension(options, annotations.E_Http)
	if ext == nil {
		return nil
	}
	return ext.(*annotations.HttpRule)
}

func parseHTTPRule(method *protogen.Method, rule *annotations.HttpRule) *routeInfo {
	var httpMethod, pattern string
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		httpMethod = "GET"
		pattern = p.Get
	case *annotations.HttpRule_Post:
		httpMethod = "POST"
		pattern = p.Post
	case *annotations.HttpRule_Put:
		httpMethod = "PUT"
		pattern = p.Put
	case *annotations.HttpRule_Delete:
		httpMethod = "DELETE"
		pattern = p.Delete
	case *annotations.HttpRule_Patch:
		httpMethod = "PATCH"
		pattern = p.Patch
	default:
		return nil
	}

	pathVars, serveMuxPath, ok := parsePathPattern(pattern)
	if !ok {
		return nil
	}

	return &routeInfo{
		rpcMethod:    string(method.Desc.Name()),
		method:       httpMethod,
		pattern:      pattern,
		serveMuxPath: serveMuxPath,
		pathVars:     pathVars,
		bodyField:    rule.Body,
		inputType:    method.Input,
		outputType:   method.Output,
	}
}

func parsePathPattern(pattern string) ([]pathVar, string, bool) {
	var pathVars []pathVar
	var result strings.Builder
	i := 0

	for i < len(pattern) {
		if pattern[i] == '{' {
			end := strings.IndexByte(pattern[i:], '}')
			if end == -1 {
				result.WriteByte(pattern[i])
				i++
				continue
			}

			placeholder := pattern[i+1 : i+end]
			fieldPath := placeholder
			varPattern := ""
			hasWildcard := false
			isRestOfPath := false
			prefix := ""

			if name, pat, found := strings.Cut(placeholder, "="); found {
				fieldPath = name
				varPattern = pat
				starCount := strings.Count(pat, "*")
				hasWildcard = starCount > 0
				isRestOfPath = starCount > 1 || (starCount == 1 && !strings.HasSuffix(pat, "*"))

				if idx := strings.Index(varPattern, "*"); idx >= 0 {
					prefix = varPattern[:idx]
				} else {
					prefix = varPattern
				}
				result.WriteString(prefix)
			}

			useWildcard := isRestOfPath

			sanitizedName := fieldPath
			if lastDot := strings.LastIndex(fieldPath, "."); lastDot >= 0 {
				sanitizedName = fieldPath[lastDot+1:]
			}

			result.WriteString("{")
			result.WriteString(sanitizedName)
			if useWildcard {
				result.WriteString("...")
			}
			result.WriteString("}")

			pathVars = append(pathVars, pathVar{
				name:      sanitizedName,
				fieldPath: fieldPath,
				prefix:    prefix,
				wildcard:  hasWildcard,
			})

			i += end + 1
		} else {
			result.WriteByte(pattern[i])
			i++
		}
	}

	return pathVars, result.String(), true
}

func hasOnlyStringPathParams(route *routeInfo, inputMsg *protogen.Message) bool {
	for _, pv := range route.pathVars {
		field := findFieldByPath(pv.fieldPath, inputMsg)
		if field == nil {
			continue
		}
		if field.Desc.Kind().String() != "string" {
			return false
		}
	}
	return true
}

func findFieldByPath(fieldPath string, msg *protogen.Message) *protogen.Field {
	parts := strings.Split(fieldPath, ".")
	currentMsg := msg

	for i, part := range parts {
		var found *protogen.Field
		for _, f := range currentMsg.Fields {
			if string(f.Desc.Name()) == part {
				found = f
				break
			}
		}
		if found == nil {
			return nil
		}
		if i == len(parts)-1 {
			return found
		}
		if found.Message == nil {
			return nil
		}
		currentMsg = found.Message
	}
	return nil
}

func generateServiceBody(g *protogen.GeneratedFile, service *protogen.Service, routes []routeInfo) {
	serviceName := service.GoName
	className := serviceName + "AIPClient"

	g.P("export class ", className, " {")
	g.P("  private readonly baseUrl: string;")
	g.P("  private readonly headers: Record<string, string>;")
	g.P("  private readonly fetch: typeof fetch;")
	g.P("  private readonly registry: Registry;")
	g.P()
	g.P("  constructor(baseUrl: string, options: AIPClientOptions) {")
	g.P("    this.baseUrl = baseUrl.replace(/\\/$/, \"\");")
	g.P("    this.headers = options.headers ?? {};")
	g.P("    this.fetch = options.fetch ?? globalThis.fetch;")
	g.P("    this.registry = options.registry;")
	g.P("  }")
	g.P()

	for _, route := range routes {
		generateTSMethod(g, route)
	}

	g.P("}")
	g.P()
}

func generateSSEHelper(g *protogen.GeneratedFile) {
	g.P("async function* streamSSE<T>(")
	g.P("  fetchFn: typeof fetch,")
	g.P("  url: string,")
	g.P("  procedure: string,")
	g.P("  message: unknown,")
	g.P("  headers: Record<string, string>,")
	g.P("  signal?: AbortSignal,")
	g.P("  parse: (data: string) => T = (d) => JSON.parse(d),")
	g.P("): AsyncGenerator<T> {")
	g.P("  const response = await fetchFn(url, {")
	g.P("    method: \"POST\",")
	g.P("    headers: { ...headers, \"Content-Type\": \"application/json\", Accept: \"text/event-stream\" },")
	g.P("    body: JSON.stringify({ procedure, header: { \"Content-Type\": [\"application/connect+json\"] }, message }),")
	g.P("    signal,")
	g.P("  });")
	g.P()
	g.P("  if (!response.ok) {")
	g.P("    throw await parseErrorResponse(response);")
	g.P("  }")
	g.P()
	g.P("  const reader = response.body?.getReader();")
	g.P("  if (!reader) throw new Error(\"No response body\");")
	g.P("  const decoder = new TextDecoder();")
	g.P("  let buffer = \"\";")
	g.P("  let flags = 0;")
	g.P("  let dataLines: string[] = [];")
	g.P()
	g.P("  let trailerError: AIPError | undefined;")
	g.P("  function processLine(line: string) {")
	g.P("    const trimmed = line.replace(/\\r$/, \"\");")
	g.P("    if (trimmed === \"\") {")
	g.P("      if (dataLines.length > 0) {")
	g.P("        const data = dataLines.join(\"\\n\");")
	g.P("        if ((flags & 2) !== 0) {")
	g.P("          try {")
	g.P("            const trailer = JSON.parse(data);")
	g.P("            if (trailer.error) {")
	g.P("              const code = codeFromString[trailer.error.code] ?? (httpStatusToCode[500] ?? 13);")
	g.P("              trailerError = new AIPError(code, trailer.error.message ?? JSON.stringify(trailer.error));")
	g.P("            }")
	g.P("          } catch { /* malformed trailer, ignore */ }")
	g.P("        } else {")
	g.P("          pending.push(parse(data));")
	g.P("        }")
	g.P("        dataLines = [];")
	g.P("        flags = 0;")
	g.P("      }")
	g.P("      return;")
	g.P("    }")
	g.P("    if (trimmed.startsWith(\":flags \")) { flags = parseInt(trimmed.slice(7), 10) || 0; return; }")
	g.P("    if (trimmed.startsWith(\":\")) return;")
	g.P("    if (trimmed.startsWith(\"data: \")) dataLines.push(trimmed.slice(6));")
	g.P("    else if (trimmed.startsWith(\"data:\")) dataLines.push(trimmed.slice(5));")
	g.P("  }")
	g.P()
	g.P("  const pending: T[] = [];")
	g.P("  try {")
	g.P("    for (;;) {")
	g.P("      const { done, value } = await reader.read();")
	g.P("      if (done) break;")
	g.P("      buffer += decoder.decode(value, { stream: true });")
	g.P("      const lines = buffer.split(\"\\n\");")
	g.P("      buffer = lines.pop() ?? \"\";")
	g.P("      for (const line of lines) processLine(line);")
	g.P("      for (const item of pending) yield item;")
	g.P("      pending.length = 0;")
	g.P("      if (trailerError) throw trailerError;")
	g.P("    }")
	g.P("    if (buffer) processLine(buffer);")
	g.P("    processLine(\"\");")
	g.P("    for (const item of pending) yield item;")
	g.P("    if (trailerError) throw trailerError;")
	g.P("  } finally {")
	g.P("    reader.cancel().catch(() => {});")
	g.P("  }")
	g.P("}")
	g.P()
}

func generateTSMethod(g *protogen.GeneratedFile, route routeInfo) {
	methodName := lowerFirst(route.rpcMethod)
	inputTypeName := string(route.inputType.Desc.Name())
	outputTypeName := string(route.outputType.Desc.Name())
	inputType := "pb." + inputTypeName
	outputType := "pb." + outputTypeName

	if route.streaming {
		generateTSStreamingMethod(g, route, methodName, inputTypeName, inputType, outputTypeName, outputType)
		return
	}

	g.P("  async ", methodName, "(")
	g.P("    request: ", inputType, " | MessageInitShape<typeof pb.", inputTypeName, "Schema>,")
	g.P("    options: { headers?: Record<string, string>; signal?: AbortSignal } = {},")
	g.P("  ): Promise<", outputType, "> {")
	g.P("    const msg = create(pb.", inputTypeName, "Schema, request as MessageInitShape<typeof pb.", inputTypeName, "Schema>);")

	if len(route.pathVars) == 0 {
		g.P("    const url = `${this.baseUrl}", route.serveMuxPath, "`;")
	} else {
		g.P("    let url = `${this.baseUrl}", route.serveMuxPath, "`;")
		for _, pv := range route.pathVars {
			fieldAccessor := tsFieldAccessor(pv.fieldPath)
			placeholder := "{" + pv.name
			if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
				placeholder += "..."
			}
			placeholder += "}"

			if pv.prefix != "" {
				g.P("    url = url.replace(\"", placeholder, "\", (", fieldAccessor, " ?? \"\").replace(\"", pv.prefix, "\", \"\"));")
			} else {
				g.P("    url = url.replace(\"", placeholder, "\", ", fieldAccessor, " ?? \"\");")
			}
		}
	}
	g.P()

	if route.method == "GET" || route.method == "DELETE" {
		g.P("    const params = new URLSearchParams();")
		generateTSQueryParams(g, route)
		g.P("    const queryString = params.toString();")
		g.P("    const finalUrl = queryString ? `${url}?${queryString}` : url;")
		g.P()
		g.P("    const response = await this.fetch(finalUrl, {")
		g.P("      method: \"", route.method, "\",")
		g.P("      headers: {")
		g.P("        ...this.headers,")
		g.P("        ...options.headers,")
		g.P("        Accept: \"application/json\",")
		g.P("      },")
		g.P("      signal: options.signal,")
		g.P("    });")
	} else {
		g.P("    const response = await this.fetch(url, {")
		g.P("      method: \"", route.method, "\",")
		g.P("      headers: {")
		g.P("        ...this.headers,")
		g.P("        ...options.headers,")
		g.P("        \"Content-Type\": \"application/json\",")
		g.P("        Accept: \"application/json\",")
		g.P("      },")
		g.P("      body: JSON.stringify(toJson(pb.", inputTypeName, "Schema, msg, { registry: this.registry })),")
		g.P("      signal: options.signal,")
		g.P("    });")
	}

	g.P()
	g.P("    if (!response.ok) {")
	g.P("      throw await parseErrorResponse(response);")
	g.P("    }")
	g.P()
	g.P("    const data = await response.json();")
	g.P("    return fromJsonAny(pb.", outputTypeName, "Schema, data, this.registry);")
	g.P("  }")
	g.P()
}

func generateTSStreamingMethod(g *protogen.GeneratedFile, route routeInfo, methodName, inputTypeName, inputType, outputTypeName, outputType string) {
	g.P("  async *", methodName, "(")
	g.P("    request: ", inputType, " | MessageInitShape<typeof pb.", inputTypeName, "Schema>,")
	g.P("    options: { headers?: Record<string, string>; signal?: AbortSignal } = {},")
	g.P("  ): AsyncGenerator<", outputType, "> {")
	g.P("    const msg = create(pb.", inputTypeName, "Schema, request as MessageInitShape<typeof pb.", inputTypeName, "Schema>);")

	if len(route.pathVars) == 0 {
		g.P("    const url = `${this.baseUrl}", route.serveMuxPath, "`;")
	} else {
		g.P("    let url = `${this.baseUrl}", route.serveMuxPath, "`;")
		for _, pv := range route.pathVars {
			fieldAccessor := tsFieldAccessor(pv.fieldPath)
			placeholder := "{" + pv.name
			if pv.wildcard && strings.Contains(route.serveMuxPath, pv.name+"...") {
				placeholder += "..."
			}
			placeholder += "}"
			if pv.prefix != "" {
				g.P("    url = url.replace(\"", placeholder, "\", (", fieldAccessor, " ?? \"\").replace(\"", pv.prefix, "\", \"\"));")
			} else {
				g.P("    url = url.replace(\"", placeholder, "\", ", fieldAccessor, " ?? \"\");")
			}
		}
	}

	g.P("    yield* streamSSE(")
	g.P("      this.fetch,")
	g.P("      url,")
	g.P("      \"", route.procedure, "\",")
	g.P("      toJson(pb.", inputTypeName, "Schema, msg, { registry: this.registry }),")
	g.P("      { ...this.headers, ...options.headers },")
	g.P("      options.signal,")
	g.P("      (data) => fromJson(pb.", outputTypeName, "Schema, JSON.parse(data), { registry: this.registry }),")
	g.P("    );")
	g.P("  }")
	g.P()
}

func generateTSQueryParams(g *protogen.GeneratedFile, route routeInfo) {
	pathVarFields := make(map[string]bool)
	for _, pv := range route.pathVars {
		pathVarFields[pv.fieldPath] = true
	}

	for _, field := range route.inputType.Fields {
		fieldPath := string(field.Desc.Name())
		if pathVarFields[fieldPath] {
			continue
		}

		fieldAccessor := "request." + snakeToCamel(fieldPath)
		jsonName := field.Desc.JSONName()

		switch field.Desc.Kind().String() {
		case "string":
			g.P("    if (", fieldAccessor, ") params.set(\"", jsonName, "\", ", fieldAccessor, ");")
		case "int32", "uint32":
			g.P("    if (", fieldAccessor, " !== 0 && ", fieldAccessor, " !== undefined) params.set(\"", jsonName, "\", String(", fieldAccessor, "));")
		case "int64", "uint64":
			g.P("    if (", fieldAccessor, " && ", fieldAccessor, " !== undefined) params.set(\"", jsonName, "\", String(", fieldAccessor, "));")
		case "float", "double":
			g.P("    if (", fieldAccessor, " !== 0 && ", fieldAccessor, " !== undefined) params.set(\"", jsonName, "\", String(", fieldAccessor, "));")
		case "bool":
			g.P("    if (", fieldAccessor, ") params.set(\"", jsonName, "\", \"true\");")
		case "enum":
			g.P("    if (", fieldAccessor, " !== 0 && ", fieldAccessor, " !== undefined) params.set(\"", jsonName, "\", String(", fieldAccessor, "));")
		}
	}
}

func tsFieldAccessor(fieldPath string) string {
	parts := strings.Split(fieldPath, ".")
	var sb strings.Builder
	sb.WriteString("request")
	for i, part := range parts {
		// First part uses regular access (request is always defined)
		// Subsequent parts use optional chaining (intermediate objects may be undefined)
		if i == 0 {
			sb.WriteString(".")
		} else {
			sb.WriteString("?.")
		}
		sb.WriteString(snakeToCamel(part))
	}
	return sb.String()
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
